### ISSUE TITLE
Bug in bootstrap.php.cache / Wallabag v2.0.3 / 1st lauch

### ISSUE THREAD

**Issue by DoumeDuSud** [wallabag/wallabag#2015]
### Issue details

After installation of Wallabag I have this error :

```
( ! ) Parse error: syntax error, unexpected '{' in E:\prog-portable\UWamp\www\wall\var\bootstrap.php.cache on line 2111
Call Stack
#	Time	Memory	Function	Location
1	0.0000	145416	{main}( )	..\app.php:0
```
and on the apache log:
````
`Tue May 03 09:05:11.794167 2016] [ssl:warn] [pid 3000:tid 364] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Tue May 03 09:05:11.809768 2016] [mpm_winnt:notice] [pid 3000:tid 364] AH00354: Child: Starting 64 worker threads.
[Tue May 03 09:05:15.553816 2016] [:error] [pid 3000:tid 1184] [client ::1:60495] PHP Parse error:  syntax error, unexpected '{' in E:\\prog-portable\\UWamp\\www\\wall\\var\\bootstrap.php.cache on line 2111
[Tue May 03 09:05:15.553816 2016] [:error] [pid 3000:tid 1184] [client ::1:60495] PHP Stack trace:
[Tue May 03 09:05:15.553816 2016] [:error] [pid 3000:tid 1184] [client ::1:60495] PHP   1. {main}() E:\\prog-portable\\UWamp\\www\\wall\\web\\app.php:0
````

### Environment

* wallabag version (or git revision) that exhibits the issue: **2.0.3**
* Install wallabag: **by downloading the package for selfhosting**
* php version: **5.4.31** 

> Edit after test: **on PHP 7.0.6 no trouble anymore**, it's working properly
> When I come back to PHP 5.5.15 I have this on my error Apache log:
```
[Tue May 03 10:58:18.035893 2016] [:error] [pid 4392:tid 1176] [client ::1:62052] PHP   1. {main}() E:\\prog-portable\\UWamp\\www\\wall\\web\\app.php:0
[Tue May 03 10:58:18.035893 2016] [:error] [pid 4392:tid 1176] [client ::1:62052] PHP   2. Symfony\\Component\\HttpKernel\\Kernel->handle() E:\\prog-portable\\UWamp\\www\\wall\\web\\app.php:28
[Tue May 03 10:58:18.035893 2016] [:error] [pid 4392:tid 1176] [client ::1:62052] PHP   3. Symfony\\Component\\HttpKernel\\HttpKernel->handle() E:\\prog-portable\\UWamp\\www\\wall\\var\\bootstrap.php.cache:2306
[Tue May 03 10:58:18.035893 2016] [:error] [pid 4392:tid 1176] [client ::1:62052] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() E:\\prog-portable\\UWamp\\www\\wall\\var\\bootstrap.php.cache:2955
[Tue May 03 10:58:18.035893 2016] [:error] [pid 4392:tid 1176] [client ::1:62052] PHP   5. Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch() E:\\prog-portable\\UWamp\\www\\wall\\var\\bootstrap.php.cache:2982
[Tue May 03 10:58:18.035893 2016] [:error] [pid 4392:tid 1176] [client ::1:62052] PHP   6. Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch() E:\\prog-portable\\UWamp\\www\\wall\\var\\cache\\prod\\classes.php:2085
[Tue May 03 10:58:18.035893 2016] [:error] [pid 4392:tid 1176] [client ::1:62052] PHP   7. call_user_func:{E:\\prog-portable\\UWamp\\www\\wall\\var\\cache\\prod\\classes.php:2167}() E:\\prog-portable\\UWamp\\www\\wall\\var\\cache\\prod\\classes.php:2167
[Tue May 03 10:58:18.035893 2016] [:error] [pid 4392:tid 1176] [client ::1:62052] PHP   8. Symfony\\Component\\HttpKernel\\EventListener\\RouterListener->onKernelRequest() E:\\prog-portable\\UWamp\\www\\wall\\var\\cache\\prod\\classes.php:2167
[Tue May 03 10:58:18.035893 2016] [:error] [pid 4392:tid 1176] [client ::1:62052] PHP   9. Monolog\\Logger->info() E:\\prog-portable\\UWamp\\www\\wall\\var\\cache\\prod\\classes.php:2373
[Tue May 03 10:58:18.035893 2016] [:error] [pid 4392:tid 1176] [client ::1:62052] PHP  10. Monolog\\Logger->addRecord() E:\\prog-portable\\UWamp\\www\\wall\\var\\cache\\prod\\classes.php:6319
[Tue May 03 10:58:18.035893 2016] [:error] [pid 4392:tid 1176] [client ::1:62052] PHP  11. date_default_timezone_get() E:\\prog-portable\\UWamp\\www\\wall\\var\\cache\\prod\\classes.php:6226
[Tue May 03 10:58:18.063896 2016] [:error] [pid 4392:tid 1176] [client ::1:62052] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to start the session because headers have already been sent by "E:\\prog-portable\\UWamp\\www\\wall\\var\\cache\\prod\\classes.php" at line 6226.' in E:\\prog-portable\\UWamp\\www\\wall\\var\\cache\\prod\\classes.php:110\nStack trace:\n#0 E:\\prog-portable\\UWamp\\www\\wall\\var\\cache\\prod\\classes.php(178): Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage->start()\n#1 E:\\prog-portable\\UWamp\\www\\wall\\var\\cache\\prod\\classes.php(441): Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage->getBag('attributes')\n#2 E:\\prog-portable\\UWamp\\www\\wall\\src\\Wallabag\\CoreBundle\\EventListener\\LocaleListener.php(33): Symfony\\Component\\HttpFoundation\\Session\\Session->get('_locale', 'en')\n#3 [internal function]: Wallabag\\CoreBundle\\EventListener\\LocaleListener->onKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#4 E:\\prog-portable\\UWamp\\www\\ in E:\\prog-portable\\UWamp\\www\\wall\\var\\cache\\prod\\classes.php on line 110
```

* OS: Windows 7 32bits with [Uwamp](http://www.uwamp.com/fr/)
* type of hosting: **dedicated**
* which storage system you choose at install: **SQLite**

### Steps to reproduce/test case

1. I check all the [dependencies request](http://doc.wallabag.org/en/master/user/installation.html) => ok
2. Made the Virtual Host: => ok (listen on port 8080)
3. Go to http://localhost:8080/ => the error message appears

**Comment by j0k3r** [comment]
PHP version must be >=5.5.9.
That's why it doesn't work on PHP 5.4.31 and it works on PHP 7.

It's stated in the documentation page: http://doc.wallabag.org/en/master/user/installation.html

> wallabag is compatible with PHP >= 5.5, including PHP 7.

**Comment by tcitworld** [comment]
Note that Uwamp's latest version brings php 5.6 or 7.0. Time to update ! :)

**Comment by DoumeDuSud** [comment]
À désolé pour le manque d'attentions😑 @tcitworld  @j0k3r 
Bonne continuation pour cette belle application 😊
Ouaip ça y est php7 est en route
