### ISSUE TITLE
Beign able to re-fetch content for a list of articles

### ISSUE THREAD

**Issue by bmillemathias** [wallabag/wallabag#2042]
### Issue details
I've installed wallabag 2 and I've just imported an export from wallabag 1 which dates from November. Now I'd like to fetch the content for the articles to update it with the new wallabag fetch code but there is no option for that.

### Environment

* wallabag version: 2.0.4
* How did you install wallabag? ```git clone```
* Last wallabag version that did not exhibit the issue: N/A
* php version: ```7.0.4-7ubuntu2```
* OS: Ubuntu 16.04
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install : MySQL

### Steps to reproduce/test case
N/A

**Comment by j0k3r** [comment]
You have the ability to re-fetch manually content per content.
You have a little reload button on the sidebar when you are viewing a content.
See the doc: http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-try-to-re-fetch-this-article

I think we'll implement the multiple re-fetch when we'll have async available.

**Comment by bmillemathias** [comment]
This is somewhat related to issue #1842

**Comment by milkywade** [comment]
Just stumbled upon this issue after migrating some articles.

Going one by one, when you have hundreds of entries, it's simply not operational.

Is there not a procedure that could be called to refetch the whole DB ?

**Comment by Kdecherf** [comment]
@milkywade `bin/console wallabag:entry:reload` may be what's your looking for

**Comment by markwaters** [comment]
When I run the above command I get -

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Did you forget a "use" statement for another namespace? in /var/www/wallabag.info/app/AppKernel.php:49
Stack trace:
#0 /var/www/wallabag.info/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(448): AppKernel->registerBundles()
#1 /var/www/wallabag.info/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/wallabag.info/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(60): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/wallabag.info/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(122): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/wallabag.info/bin/console( in /var/www/wallabag.info/app/AppKernel.php on line 49
```

Any ideas ?

**Comment by j0k3r** [comment]
```
bin/console wallabag:entry:reload --env=prod
```

**Comment by markwaters** [comment]
Thank you!

**Comment by tghdev** [comment]
I suggest a new sidebar entry, e.g. _unfetched_, where all unfetched articles show up with a refetch button at the top bar to initiate a batch refetch for all articles within this section.
I don't like the idea of refetching the whole database, because already fetched, but source-deleted entries, could be overwritten and thus get unfetched as well. But I'm not sure about that. Maybe someone clarify. Thanks

**Comment by mattbk** [comment]
It would be helpful to refetch content of a list generated by search (e.g, search by domain, then refetch for all the results). If that's not possible, adding a "refetch" button next to "mark as read", "star", and "delete" button would work.
