### ISSUE TITLE
Switching from Apache to Nginx: Error 500

### ISSUE THREAD

**Issue by theced7** [wallabag/wallabag#2203]
After running Wallabag with Apache for quite some time I've decided to switch to Nginx instead. 

Thus, I've used the official nginx config:

```
root@ip-:/var/log/nginx# cat /etc/nginx/sites-enabled/wallabag
server {
    server_name wallabag.mydomain.com; # Changed that to my acutal domain of course
    root /var/www/html/wallabag/web;

    location / {
        # try to serve file directly, fallback to app.php
        try_files $uri /app.php$is_args$args;
    }
    location ~ ^/app\.php(/|$) {
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        # When you are using symlinks to link the document root to the
        # current version of your application, you should pass the real
        # application path instead of the path to the symlink to PHP
        # FPM.
        # Otherwise, PHP's OPcache may not properly detect changes to
        # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
        # for more information).
        fastcgi_param  SCRIPT_FILENAME  $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        # Prevents URIs that include the front controller. This will 404:
        # http://domain.tld/app.php/some-path
        # Remove the internal directive to allow URIs like this
        internal;
    }

    error_log /var/log/nginx/wallabag_error.log;
    access_log /var/log/nginx/wallabag_access.log;
}
```

However, when trying to access wallabag._mydomain_.com i get a 500 HTTP Error and the following wallabag_error.log: 

```
root@ip:/var/log/nginx# tail -f wallabag_error.log
2016/07/24 12:41:00 [error] 5666#0: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/var/www/html/wallabag/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml&quot; in /var/www/html/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/var/www/html/wallabag/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml&quot; in /var/www/html/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
PHP message: PHP Fatal error:  Uncaught exception 'Doctrine\Common\Persistence\Mapping\MappingException' with message 'Invalid mapping file 'FOS.UserBundle.Model.User.orm.xml' for class 'FOS\UserBundle\Model\User'.' in /var/www/html/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:86
Stack trace:
#0 /var/www/html/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php(117): Doctrine\Common\Persistence\Mapping\MappingException::invalidMappingFile('FOS\\UserBundle\\...', 'FOS.UserBundle....')
#1 /var/www/html/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php(58): Doctrine\Common\Persistence\Mapping\Driver\FileDriver->getElement('FOS\\UserBundle\\...')
#2 /var/www/html/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(102): Doctrine\ORM\Mapping\Driver\XmlDriver->loadMetadataForClass('FOS\\UserBundle\\...', Object(Doctrine\ORM\Mapping\ClassMetadata))
#3" while reading response header from upstream, client: IP, server: wallabag.mydomain.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "wallabag.mydomain.com"
```
### Environment
- wallabag version (or git revision) that exhibits the issue: "Already up-to-date"
- How did you install wallabag? git clone
- Last wallabag version that did not exhibit the issue (if applicable):
- php version: PHP 5.6.23-0+deb8u1
- OS: Debian Jessie
- type of hosting (shared or dedicated): dedicated 
- which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

**Comment by j0k3r** [comment]
This is a known issue but sadly it's not really on our side, but here is a work around: https://github.com/wallabag/wallabag/issues/1828#issuecomment-205241568
