### ISSUE TITLE
Installation Error with composer v2.1.5

### ISSUE THREAD

**Issue by sigmap** [wallabag/wallabag#2744]
### Issue details

Attempted install with composer got error message
```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: wallabag_craue_config_setting' in C:\xampp\htdocs\wallabag-2.1.5\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:77 Stack trace: #0 C:\xampp\htdocs\wallabag-2.1.5\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(77): PDO->prepare('SELECT t0.name ...', Array) #1 C:\xampp\htdocs\wallabag-2.1.5\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(825): Doctrine\DBAL\Driver\PDOConnection->prepare('SELECT t0.name ...') #2 C:\xampp\htdocs\wallabag-2.1.5\vendor\doctrine\orm\lib\Doctrine\ORM\Persisters\Entity\BasicEntityPersister.php(712): Doctrine\DBAL\Connection->executeQuery('SELECT t0.name ...', Array, Array) #3 C:\xampp\htdocs\wallabag-2.1.5\vendor\doctrine\orm\lib\Doctrine\ORM\EntityRepository.php(196): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL) #4 C:\xampp\htdocs\wallabag-2.1.5\vendor\craue\config-bundle\Util\Config.php(39): Doc in C:\xampp\htdocs\wallabag-2.1.5\var\cache\prod\classes.php on line 5922
```

### Environment
* wallabag version: 2.1.5
* download from releases
* php version: 5.6.28(xampp)
* OS: Windows
Shared hosting
Chose SQLite as assumed it was suggested

### Steps to reproduce/test case
Downloaded release 2.1.5
ensured all php dependencies were installed, installed composer in wallabag directory
ran `curl -s http://getcomposer.org/installer | php` followed by `php composer.phar install` and filled in entries as suggested with some exceptions (eg, secret)
```
Some parameters are missing. Please provide them.
database_driver (pdo_sqlite): 
database_host (127.0.0.1): 
database_port (null): 
database_name (symfony): 
database_user (root): 
database_password (null): 
database_path ('%kernel.root_dir%/../data/db/wallabag.sqlite'): 
database_table_prefix (wallabag_): 
database_socket (null): 
mailer_transport (smtp): 
mailer_host (127.0.0.1): 
mailer_user (null): 
mailer_password (null): 
locale (en): 
secret (ovmpmAWXRCabNlMgzlzFXDYmCFfzGv):
twofactor_auth (true): 
twofactor_sender (no-reply@wallabag.org): 
fosuser_registration (true): 
fosuser_confirmation (true): 
from_email (no-reply@wallabag.org): 
rss_limit (50): 
rabbitmq_host (localhost): 
rabbitmq_port (5672): 
rabbitmq_user (guest): 
rabbitmq_password (guest): 
redis_scheme (tcp): 
redis_host (localhost): 
redis_port (6379): 
redis_path (null): 
```

**Comment by j0k3r** [comment]
At which step did you got that error message?
Could you paste the whole output of your installation process?

**Comment by sigmap** [comment]
Accessing wall.localhost.

##Installation process
downloaded 2.1.5
installed composer into wallabag's directory
php composer.phar install
   "some parameters missing" filled in suggested entries with a few changes, `secret` and `database path` where the two changed, everything else was entered as suggested
accessed https://wall.localhost, redirected to to wall.localhost/login and that was when I saw the error message in my browser,

**Comment by sigmap** [comment]
renamed `Vendor` to and ran `php composer.phar install`
```
$ php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 131 installs, 0 updates, 0 removals
  - Installing behat/transliterator (v1.1.0) Loading from cache
  - Installing twig/twig (v1.28.1) Loading from cache
  - Installing symfony/polyfill-util (v1.3.0) Loading from cache
  - Installing paragonie/random_compat (v1.4.1) Loading from cache
  - Installing symfony/polyfill-php70 (v1.3.0) Loading from cache
  - Installing symfony/polyfill-php56 (v1.3.0) Loading from cache
  - Installing symfony/polyfill-mbstring (v1.3.0) Loading from cache
  - Installing symfony/symfony (v3.1.7) Loading from cache
  - Installing symfony/polyfill-intl-icu (v1.3.0) Loading from cache
  - Installing psr/log (1.0.2) Loading from cache
  - Installing psr/cache (1.0.1) Loading from cache
  - Installing doctrine/lexer (v1.0.1) Loading from cache
  - Installing doctrine/inflector (v1.1.0) Loading from cache
  - Installing doctrine/collections (v1.3.0) Loading from cache
  - Installing doctrine/cache (v1.6.1) Loading from cache
  - Installing doctrine/annotations (v1.2.7) Loading from cache
  - Installing doctrine/common (v2.6.1) Loading from cache
  - Installing craue/config-bundle (1.4.1) Loading from cache
  - Installing doctrine/doctrine-cache-bundle (1.3.0) Loading from cache
  - Installing zendframework/zend-eventmanager (3.0.1) Loading from cache
  - Installing zendframework/zend-code (2.6.3) Loading from cache
  - Installing ocramius/proxy-manager (1.0.2) Loading from cache
  - Installing doctrine/dbal (v2.5.5) Loading from cache
    Skipped installation of bin bin/doctrine-dbal for package doctrine/dbal: name conflicts with an existing file
  - Installing doctrine/migrations (1.4.1) Loading from cache
    Skipped installation of bin bin/doctrine-migrations for package doctrine/migrations: name conflicts with an existing fil
e
  - Installing jdorn/sql-formatter (v1.2.17) Loading from cache
  - Installing doctrine/doctrine-bundle (1.6.4) Loading from cache
  - Installing doctrine/doctrine-migrations-bundle (v1.2.0) Loading from cache
  - Installing friendsofsymfony/oauth2-php (1.2.1) Loading from cache
  - Installing friendsofsymfony/oauth-server-bundle (1.5.2) Loading from cache
  - Installing willdurand/negotiation (v2.2.1) Loading from cache
  - Installing willdurand/jsonp-callback-validator (v1.1.0) Loading from cache
  - Installing friendsofsymfony/rest-bundle (2.1.0) Loading from cache
  - Installing grandt/relativepath (1.0.2) Loading from cache
  - Installing grandt/binstring (1.0.0) Loading from cache
  - Installing grandt/phpzipmerge (1.0.4) Loading from cache
  - Installing phpzip/phpzip (2.0.8) Loading from cache
  - Installing grandt/phpresizegif (1.0.3) Loading from cache
  - Installing grandt/phpepub (4.0.7.1) Loading from cache
  - Installing react/promise (v2.4.1) Loading from cache
  - Installing guzzlehttp/streams (3.0.0) Loading from cache
  - Installing guzzlehttp/ringphp (1.1.0) Loading from cache
  - Installing hoa/exception (1.16.11.08) Loading from cache
  - Installing hoa/consistency (1.16.03.03) Loading from cache
  - Installing hoa/event (1.16.11.19) Loading from cache
  - Installing hoa/iterator (2.16.11.19) Loading from cache
  - Installing hoa/visitor (2.16.01.11) Loading from cache
  - Installing hoa/ustring (4.16.01.11) Loading from cache
  - Installing hoa/protocol (1.16.07.07) Loading from cache
  - Installing hoa/zformat (1.16.03.15) Loading from cache
  - Installing hoa/regex (1.16.09.06) Loading from cache
  - Installing hoa/math (1.16.08.29) Loading from cache
  - Installing hoa/stream (1.16.11.08) Loading from cache
  - Installing hoa/file (1.16.01.15) Loading from cache
  - Installing hoa/compiler (3.16.10.24) Loading from cache
  - Installing hoa/ruler (2.16.10.24) Loading from cache
  - Installing incenteev/composer-parameter-handler (v2.1.2) Loading from cache
  - Installing true/punycode (v2.1.1) Loading from cache
  - Installing tecnickcom/tcpdf (6.2.12) Loading from cache
  - Installing smalot/pdfparser (v0.9.26) Loading from cache
  - Installing simplepie/simplepie (1.3.1) Loading from cache
  - Installing monolog/monolog (1.21.0) Loading from cache
  - Installing j0k3r/safecurl (2.0.2) Loading from cache
  - Installing j0k3r/php-readability (1.1.3) Loading from cache
  - Installing j0k3r/graby-site-config (1.0.28) Loading from cache
  - Installing htmlawed/htmlawed (1.1.22) Loading from cache
  - Installing guzzlehttp/guzzle (5.3.1) Loading from cache
  - Installing j0k3r/graby (1.5.1) Loading from cache
  - Installing javibravo/simpleue (1.0.0) Loading from cache
  - Installing phpoption/phpoption (1.5.0) Loading from cache
  - Installing phpcollection/phpcollection (0.5.0) Loading from cache
  - Installing jms/parser-lib (1.0.0) Loading from cache
  - Installing jms/metadata (1.5.1) Loading from cache
  - Installing doctrine/instantiator (1.0.5) Loading from cache
  - Installing jms/serializer (1.4.2) Loading from cache
  - Installing kphoen/rulerz (0.19.1) Loading from cache
  - Installing kphoen/rulerz-bundle (0.12.1) Loading from cache
  - Installing doctrine/orm (v2.5.5) Loading from cache
    Skipped installation of bin bin/doctrine for package doctrine/orm: name conflicts with an existing file
    Skipped installation of bin bin/doctrine.php for package doctrine/orm: name conflicts with an existing file
  - Installing lexik/form-filter-bundle (v5.0.1) Loading from cache
  - Installing lexik/maintenance-bundle (v2.1.1) Loading from cache
  - Installing liip/theme-bundle (1.4.1) Loading from cache
  - Installing mgargano/simplehtmldom (1.5) Loading from cache
  - Installing mnapoli/piwik-twig-extension (1.0.0) Loading from cache
  - Installing michelf/php-markdown (1.7.0) Loading from cache
  - Installing nelmio/api-doc-bundle (2.13.0) Loading from cache
  - Installing nelmio/cors-bundle (1.4.1) Loading from cache
  - Installing php-amqplib/php-amqplib (v2.6.3) Loading from cache
  - Installing php-amqplib/rabbitmq-bundle (v1.11.2) Loading from cache
  - Installing predis/predis (v1.1.1) Loading from cache
  - Installing sonata-project/google-authenticator (1.0.2) Loading from cache
  - Installing scheb/two-factor-bundle (v2.8.2) Loading from cache
  - Installing sensiolabs/security-checker (v4.0.0) Loading from cache
    Skipped installation of bin security-checker for package sensiolabs/security-checker: name conflicts with an existing fi
le
  - Installing sensio/distribution-bundle (v5.0.14) Loading from cache
  - Installing sensio/framework-extra-bundle (v3.0.16) Loading from cache
  - Installing gedmo/doctrine-extensions (v2.4.24) Loading from cache
  - Installing stof/doctrine-extensions-bundle (v1.2.2) Loading from cache
  - Installing symfony/monolog-bundle (2.12.0) Loading from cache
  - Installing swiftmailer/swiftmailer (v5.4.3) Loading from cache
  - Installing symfony/swiftmailer-bundle (v2.4.0) Loading from cache
  - Installing twig/extensions (v1.4.1) Loading from cache
  - Installing wallabag/php-mobi (1.0.1) Loading from cache
  - Installing pagerfanta/pagerfanta (v1.0.3) Loading from cache
  - Installing white-october/pagerfanta-bundle (v1.0.7) Loading from cache
  - Installing willdurand/hateoas (2.10.0) Loading from cache
  - Installing jms/serializer-bundle (1.1.0) Loading from cache
  - Installing willdurand/hateoas-bundle (1.2.0) Loading from cache
  - Installing doctrine/data-fixtures (v1.1.1) Loading from cache
  - Installing doctrine/doctrine-fixtures-bundle (2.3.0) Loading from cache
  - Installing sebastian/diff (1.4.1) Loading from cache
  - Installing friendsofphp/php-cs-fixer (v1.12.4) Loading from cache
    Skipped installation of bin php-cs-fixer for package friendsofphp/php-cs-fixer: name conflicts with an existing file
  - Installing m6web/redis-mock (v2.8.0) Loading from cache
  - Installing webmozart/assert (1.1.0) Loading from cache
  - Installing phpdocumentor/reflection-common (1.0) Loading from cache
  - Installing phpdocumentor/type-resolver (0.2) Loading from cache
  - Installing phpdocumentor/reflection-docblock (3.1.1) Loading from cache
  - Installing phpunit/php-token-stream (1.4.9) Loading from cache
  - Installing sebastian/version (1.0.6) Loading from cache
  - Installing sebastian/global-state (1.1.1) Loading from cache
  - Installing sebastian/recursion-context (1.0.2) Loading from cache
  - Installing sebastian/exporter (1.2.2) Loading from cache
  - Installing sebastian/environment (1.3.8) Loading from cache
  - Installing sebastian/comparator (1.2.2) Loading from cache
  - Installing phpunit/php-text-template (1.2.1) Loading from cache
  - Installing phpunit/phpunit-mock-objects (2.3.8) Loading from cache
  - Installing phpunit/php-timer (1.0.8) Loading from cache
  - Installing phpunit/php-file-iterator (1.4.1) Loading from cache
  - Installing phpunit/php-code-coverage (2.2.4) Loading from cache
  - Installing phpspec/prophecy (v1.6.1) Loading from cache
  - Installing phpunit/phpunit (4.8.28) Loading from cache
    Skipped installation of bin phpunit for package phpunit/phpunit: name conflicts with an existing file
  - Installing sensio/generator-bundle (v3.1.1) Loading from cache
  - Installing symfony/phpunit-bridge (v3.1.7) Loading from cache
  - Installing friendsofsymfony/user-bundle (dev-master e168ed6) Cloning e168ed6462 from cache
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random
bytes.)
symfony/polyfill-intl-icu suggests installing ext-intl (For best performance)
doctrine/doctrine-cache-bundle suggests installing symfony/security-acl (For using this bundle to cache ACLs)
zendframework/zend-eventmanager suggests installing container-interop/container-interop (^1.1.0, to use the lazy listeners f
eature)
zendframework/zend-eventmanager suggests installing zendframework/zend-stdlib (^2.7.3 || ^3.0, to use the FilterChain featur
e)
zendframework/zend-code suggests installing zendframework/zend-stdlib (Zend\Stdlib component)
ocramius/proxy-manager suggests installing ocramius/generated-hydrator (To have very fast object to array to object conversi
on for ghost objects)
ocramius/proxy-manager suggests installing zendframework/zend-json (To have the JsonRpc adapter (Remote Object feature))
ocramius/proxy-manager suggests installing zendframework/zend-soap (To have the Soap adapter (Remote Object feature))
ocramius/proxy-manager suggests installing zendframework/zend-stdlib (To use the hydrator proxy)
ocramius/proxy-manager suggests installing zendframework/zend-xmlrpc (To have the XmlRpc adapter (Remote Object feature))
friendsofsymfony/oauth-server-bundle suggests installing doctrine/mongodb-odm-bundle (*)
friendsofsymfony/oauth-server-bundle suggests installing propel/propel-bundle (If you want to use Propel with Symfony2, then
 you will have to install the PropelBundle)
friendsofsymfony/oauth-server-bundle suggests installing willdurand/propel-typehintable-behavior (The Typehintable behavior
is useful to add type hints on generated methods, to be compliant with interfaces)
hoa/ustring suggests installing ext-intl (To get a better Hoa\Ustring::toAscii() and Hoa\Ustring::compareTo().)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
javibravo/simpleue suggests installing aws/aws-sdk-php (Allow work with AWS Simple Queue Service (SQS) queues)
kphoen/rulerz suggests installing elasticsearch/elasticsearch (To execute rules as Elasticsearch queries)
kphoen/rulerz suggests installing kphoen/rulerz-spec-builder (If you want a specification builder)
kphoen/rulerz suggests installing pomm-project/model-manager (To execute rules as Pomm queries)
kphoen/rulerz suggests installing solarium/solarium (To execute rules as Solr queries)
nelmio/api-doc-bundle suggests installing dunglas/api-bundle (For making use of resources definitions of DunglasApiBundle.)
php-amqplib/php-amqplib suggests installing ext-sockets (Use AMQPSocketConnection)
predis/predis suggests installing ext-phpiredis (Allows faster serialization and deserialization of the Redis protocol)
sensio/framework-extra-bundle suggests installing symfony/psr-http-message-bridge (To use the PSR-7 converters)
gedmo/doctrine-extensions suggests installing doctrine/mongodb-odm (to use the extensions with the MongoDB ODM)
stof/doctrine-extensions-bundle suggests installing doctrine/mongodb-odm-bundle (to use the MongoDB ODM extensions)
pagerfanta/pagerfanta suggests installing doctrine/mongodb-odm (To use the DoctrineODMMongoDBAdapter.)
pagerfanta/pagerfanta suggests installing doctrine/phpcr-odm (To use the DoctrineODMPhpcrAdapter. >= 1.1.0)
pagerfanta/pagerfanta suggests installing mandango/mandango (To use the MandangoAdapter.)
pagerfanta/pagerfanta suggests installing propel/propel1 (To use the PropelAdapter)
pagerfanta/pagerfanta suggests installing solarium/solarium (To use the SolariumAdapter.)
jms/serializer-bundle suggests installing jms/di-extra-bundle (Required to get lazy loading (de)serialization visitors, ~1.3
)
doctrine/data-fixtures suggests installing doctrine/mongodb-odm (For loading MongoDB ODM fixtures)
doctrine/data-fixtures suggests installing doctrine/phpcr-odm (For loading PHPCR ODM fixtures)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
friendsofsymfony/user-bundle suggests installing willdurand/propel-typehintable-behavior (Needed when using the propel imple
mentation)
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug true

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
```

**Comment by j0k3r** [comment]
After that, you need to run `php bin/console wallabag:install -e=prod`

**Comment by sigmap** [comment]
That worked. I probably overlooked that in the docs.  Closing.
