### ISSUE TITLE
Wallabag install fails with "SensioGeneratorBundle not found"

### ISSUE THREAD

**Issue by oupala** [wallabag/wallabag#2986]
### Issue details

Wallabag install fails with "SensioGeneratorBundle not found"

When installing Wallabag using composer, the install fails:

```bash
>./composer.phar install --no-dev -o --prefer-dist
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in /home/<user>/apps/wallabag-2.2.2/app/AppKernel.php on line 49
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-cmd event terminated with an exception

                                                                                                                                           
  [RuntimeException]                                                                                                                       
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                
  PHP Fatal error:  Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in /home/<user>/apps/wallabag-2.2.2/app/AppKernel.  
  php on line 49                                                                                                                           
  .                                                                                                                                        
```

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package? downloading the package
* Last wallabag version that did not exhibit the issue (if applicable): do not know (it is my first install)
* php version: 7.0
* OS: raspbian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): sqlite

### Steps to reproduce/test case

- download wallabag
- install composer
- set SYMFONY_ENV=prod
- launch `./composer.phar install --no-dev -o --prefer-dist`

**Comment by j0k3r** [comment]
Try that instead.

```
SYMFONY_ENV=prod ./composer.phar install --no-dev -o --prefer-dist
```

The missing bundle is only available in the dev requirement which means the SYMFONY_ENV wasn't found during your composer installation.

Also please, read the doc on [how to install it](http://doc.wallabag.org/en/master/user/installation.html#installation).

**Comment by oupala** [comment]
Ok it works well when defining the bash variable on the same line as the composer command.

```bash
>SYMFONY_ENV=prod ./composer.phar install --no-dev -o --prefer-dist
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 107 installs, 0 updates, 0 removals
  - Installing react/promise (v2.5.0): Downloading (100%)         
  - Installing guzzlehttp/streams (3.0.0): Downloading (100%)         
  - Installing guzzlehttp/ringphp (1.1.0): Downloading (100%)         
  - Installing guzzlehttp/guzzle (5.3.1): Downloading (100%)         
  - Installing bdunogier/guzzle-site-authenticator (dev-master 196bab1): Downloading (100%)         
  - Installing behat/transliterator (v1.1.0): Downloading (100%)         
  - Installing twig/twig (v1.32.0): Downloading (100%)         
  - Installing symfony/polyfill-util (v1.3.0): Downloading (100%)         
  - Installing paragonie/random_compat (v1.4.1): Downloading (100%)         
  - Installing symfony/polyfill-php70 (v1.3.0): Downloading (100%)         
  - Installing symfony/polyfill-php56 (v1.3.0): Downloading (100%)         
  - Installing symfony/polyfill-mbstring (v1.3.0): Downloading (100%)         
  - Installing symfony/symfony (v3.2.4): Downloading (100%)         
  - Installing symfony/polyfill-intl-icu (v1.3.0): Downloading (100%)         
  - Installing psr/log (1.0.2): Downloading (100%)         
  - Installing psr/cache (1.0.1): Downloading (100%)         
  - Installing doctrine/lexer (v1.0.1): Downloading (100%)         
  - Installing doctrine/inflector (v1.1.0): Downloading (100%)         
  - Installing doctrine/collections (v1.3.0): Downloading (100%)         
  - Installing doctrine/cache (v1.6.1): Downloading (100%)         
  - Installing doctrine/annotations (v1.2.7): Downloading (100%)         
  - Installing doctrine/common (v2.6.2): Downloading (100%)         
  - Installing craue/config-bundle (1.4.1): Downloading (100%)         
  - Installing doctrine/doctrine-cache-bundle (1.3.0): Downloading (100%)         
  - Installing zendframework/zend-eventmanager (3.0.1): Downloading (100%)         
  - Installing zendframework/zend-code (2.6.3): Downloading (100%)         
  - Installing ocramius/proxy-manager (1.0.2): Downloading (100%)         
  - Installing doctrine/dbal (v2.5.12): Downloading (100%)         
  - Installing doctrine/migrations (v1.5.0): Downloading (100%)         
  - Installing jdorn/sql-formatter (v1.2.17): Downloading (100%)         
  - Installing doctrine/doctrine-bundle (1.6.7): Downloading (100%)         
  - Installing doctrine/doctrine-migrations-bundle (v1.2.1): Downloading (100%)         
  - Installing willdurand/jsonp-callback-validator (v1.1.0): Downloading (100%)         
  - Installing friendsofsymfony/jsrouting-bundle (1.6.0): Downloading (100%)         
  - Installing friendsofsymfony/oauth2-php (1.2.1): Downloading (100%)         
  - Installing friendsofsymfony/oauth-server-bundle (1.5.2): Downloading (100%)         
  - Installing willdurand/negotiation (v2.2.1): Downloading (100%)         
  - Installing friendsofsymfony/rest-bundle (2.1.1): Downloading (100%)         
  - Installing friendsofsymfony/user-bundle (dev-master 0d70c91): Downloading (100%)         
  - Installing grandt/relativepath (1.0.2): Downloading (100%)         
  - Installing grandt/binstring (1.0.0): Downloading (100%)         
  - Installing grandt/phpzipmerge (1.0.4): Downloading (100%)         
  - Installing phpzip/phpzip (2.0.8): Downloading (100%)         
  - Installing grandt/phpresizegif (1.0.3): Downloading (100%)         
  - Installing grandt/phpepub (4.0.7.1): Downloading (100%)         
  - Installing hoa/exception (1.17.01.16): Downloading (100%)         
  - Installing hoa/consistency (1.17.01.10): Downloading (100%)         
  - Installing hoa/event (1.17.01.13): Downloading (100%)         
  - Installing hoa/iterator (2.17.01.10): Downloading (100%)         
  - Installing hoa/visitor (2.17.01.16): Downloading (100%)         
  - Installing hoa/ustring (4.17.01.16): Downloading (100%)         
  - Installing hoa/protocol (1.17.01.14): Downloading (100%)         
  - Installing hoa/zformat (1.17.01.10): Downloading (100%)         
  - Installing hoa/regex (1.17.01.13): Downloading (100%)         
  - Installing hoa/math (1.17.01.13): Downloading (100%)         
  - Installing hoa/stream (1.17.02.21): Downloading (100%)         
  - Installing hoa/file (1.17.01.13): Downloading (100%)         
  - Installing hoa/compiler (3.17.01.10): Downloading (100%)         
  - Installing hoa/ruler (2.17.01.13): Downloading (100%)         
  - Installing incenteev/composer-parameter-handler (v2.1.2): Downloading (100%)         
  - Installing wallabag/tcpdf (6.2.15): Downloading (100%)         
  - Installing true/punycode (v2.1.1): Downloading (100%)         
  - Installing smalot/pdfparser (v0.9.26): Downloading (100%)         
  - Installing simplepie/simplepie (1.3.1): Downloading (100%)         
  - Installing monolog/monolog (1.22.0): Downloading (100%)         
  - Installing j0k3r/safecurl (2.0.2): Downloading (100%)         
  - Installing j0k3r/php-readability (1.1.6): Downloading (100%)         
  - Installing j0k3r/graby-site-config (1.0.32): Downloading (100%)         
  - Installing htmlawed/htmlawed (1.1.22): Downloading (100%)         
  - Installing j0k3r/graby (1.6.0): Downloading (100%)         
  - Installing javibravo/simpleue (1.1.1): Downloading (100%)         
  - Installing phpoption/phpoption (1.5.0): Downloading (100%)         
  - Installing phpcollection/phpcollection (0.5.0): Downloading (100%)         
  - Installing jms/parser-lib (1.0.0): Downloading (100%)         
  - Installing jms/metadata (1.6.0): Downloading (100%)         
  - Installing doctrine/instantiator (1.0.5): Downloading (100%)         
  - Installing jms/serializer (1.5.0): Downloading (100%)         
  - Installing kphoen/rulerz (0.19.3): Downloading (100%)         
  - Installing kphoen/rulerz-bundle (0.13.1): Downloading (100%)         
  - Installing doctrine/orm (v2.5.6): Downloading (100%)         
  - Installing lexik/form-filter-bundle (v5.0.3): Downloading (100%)         
  - Installing liip/theme-bundle (1.4.6): Downloading (100%)         
  - Installing mgargano/simplehtmldom (1.5): Downloading (100%)         
  - Installing mnapoli/piwik-twig-extension (1.0.0): Downloading (100%)         
  - Installing michelf/php-markdown (1.7.0): Downloading (100%)         
  - Installing nelmio/api-doc-bundle (2.13.1): Downloading (100%)         
  - Installing nelmio/cors-bundle (1.4.1): Downloading (100%)         
  - Installing php-amqplib/php-amqplib (v2.6.3): Downloading (100%)         
  - Installing php-amqplib/rabbitmq-bundle (v1.12.0): Downloading (100%)         
  - Installing predis/predis (v1.1.1): Downloading (100%)         
  - Installing sonata-project/google-authenticator (1.0.2): Downloading (100%)         
  - Installing scheb/two-factor-bundle (v2.9.0): Downloading (100%)         
  - Installing sensiolabs/security-checker (v4.0.1): Downloading (100%)         
  - Installing sensio/distribution-bundle (v5.0.18): Downloading (100%)         
  - Installing sensio/framework-extra-bundle (v3.0.22): Downloading (100%)         
  - Installing gedmo/doctrine-extensions (v2.4.26): Downloading (100%)         
  - Installing stof/doctrine-extensions-bundle (v1.2.2): Downloading (100%)         
  - Installing symfony/monolog-bundle (v3.0.3): Downloading (100%)         
  - Installing swiftmailer/swiftmailer (v5.4.6): Downloading (100%)         
  - Installing symfony/swiftmailer-bundle (v2.5.1): Downloading (100%)         
  - Installing twig/extensions (v1.4.1): Downloading (100%)         
  - Installing wallabag/php-mobi (1.0.1): Downloading (100%)         
  - Installing pagerfanta/pagerfanta (v1.0.4): Downloading (100%)         
  - Installing white-october/pagerfanta-bundle (v1.0.8): Downloading (100%)         
  - Installing willdurand/hateoas (2.10.0): Downloading (100%)         
  - Installing jms/serializer-bundle (1.2.0): Downloading (100%)         
  - Installing willdurand/hateoas-bundle (1.2.0): Downloading (100%)         
Generating optimized autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Creating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
database_driver (pdo_sqlite): 
database_host (127.0.0.1): 
database_port (null): 
database_name (symfony): 
database_user (root): 
database_password (null): 
database_path ('%kernel.root_dir%/../data/db/wallabag.sqlite'): 
database_table_prefix (wallabag_): 
database_socket (null): 
database_charset (utf8): 
mailer_transport (smtp): 
mailer_host (127.0.0.1): 
mailer_user (null): 
mailer_password (null): 
locale (en): 
secret (ovsdfmslkfsdmlkfsdfmlksdfmlkepoierCFfzGv): 
twofactor_auth (true): false
twofactor_sender (no-reply@wallabag.org): 
fosuser_registration (true): 
fosuser_confirmation (true): 
from_email (no-reply@wallabag.org): 
rss_limit (50): 
rabbitmq_host (localhost): 
rabbitmq_port (5672): 
rabbitmq_user (guest): 
rabbitmq_password (guest): 
rabbitmq_prefetch_count (10): 
redis_scheme (tcp): 
redis_host (localhost): 
redis_port (6379): 
redis_path (null): 
redis_password (null): 
sites_credentials ({  }): 
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

                                                                                
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  
                                                                                

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as absolute symbolic links.

 --- ------------------------------ ------------------ 
      Bundle                         Method / Error    
 --- ------------------------------ ------------------ 
  ✔   NelmioApiDocBundle             absolute symlink  
  ✔   WhiteOctoberPagerfantaBundle   absolute symlink  
  ✔   FOSJsRoutingBundle             absolute symlink  
 --- ------------------------------ ------------------ 

                                                                                
 [OK] All assets were successfully installed.                                   
                                                                                

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
>
```

I'm trying to install wallabag, as described on a [dedicated web server](http://doc.wallabag.org/en/master/user/installation.html#on-a-dedicated-web-server-recommended-way) but without make installed. So I had a look at the `Makefile` and the at the scripts, trying to reproduce every step originally made by make.

I still have a problem at (sqlite) database creation:

```
[Tue Mar 28 03:01:24.379567 2017] [:error] [pid 10751] [client 192.168.1.102:38181] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: wallabag_craue_config_setting' in /home/<user>/wallabag-2.2.2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77\nStack trace:\n#0 /home/<user>/wallabag-2.2.2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(77): PDO->prepare('SELECT t0.name ...', Array)\n#1 /home/<user>/wallabag-2.2.2/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(844): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('SELECT t0.name ...')\n#2 /home/<user>/wallabag-2.2.2/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(712): Doctrine\\DBAL\\Connection->executeQuery('SELECT t0.name ...', Array, Array)\n#3 /home/<user>/wallabag-2.2.2/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(196): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)\n#4 /home/<user>/wallabag-2.2.2/vendor/craue/config-bundle/Util/Config.php(39): Doctrine\\ in /home/<user>/wallabag-2.2.2/src/Wallabag/CoreBundle/Resources/views/base.html.twig on line 71
```

Can you guess what's happening?

**Comment by j0k3r** [comment]
If you are on a dedicated server, why can't you install make?

You have to launch that command now:

```
php bin/console wallabag:install --env=prod
```

**Comment by oupala** [comment]
I go further with the execution of the install step that you gave me.

However, I end with an internal server error on the following url: `https://<server>/wallabag/web/login_check`

And the error displayed on the web browser is:

> Oops! An Error Occurred
> The server returned a "500 Internal Server Error".
> Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

There absolutely nothing in apache error log.

And I don't wen to install `make` for the following reasons:

1. I find that Wallabag install process is over-engineered and I try to remove useless layers
2. I'm installing all that on a raspberry 1, which is quite slow
3. I try to install wallabag using a ansible and extra-layers means more overhead (user launching ansible which launch make which launch composer which launch some an external php library: are you sure to get the root cause of the error, if there is any?)

The simplest it is, the most robust it gets.

**Comment by oupala** [comment]
I should maybe give a try to the [package with all dependencies inside](http://doc.wallabag.org/en/master/user/installation.html#on-a-shared-hosting)...
