### ISSUE TITLE
Only blank page (failed to load external entity)

### ISSUE THREAD

**Issue by slaecker** [wallabag/wallabag#3009]
### Issue details

I've tried to install Wallabag several times now during the past weeks but never had luck so I decided to open an issue. Other PHP apps like Tiny Tiny RSS, Baikal, phpMyAdmin ... work fine

After following the [install documentation](http://doc.wallabag.org/en/master/user/installation.html) I symlinked the wallabag folder /opt/git/wallabag to /var/www/html/wallabag, set ownership to www-data on the complete wallabag directory recursively and set up an Nginx vhost (copied from the install doc and adapted to my local setup), see below. I restarted Nginx and tried to access Wallabag but only get a blank page.

#### Nginx Error log

```
2017/03/24 17:30:30 [error] 6415#6415: *18 FastCGI sent in stderr: "PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/opt/git/wallabag/vendor/friendsofsymfony/oauth-server-bundle/Resources/config/doctrine/Client.orm.xml&quot; in /opt/git/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/opt/git/wallabag/vendor/friendsofsymfony/oauth-server-bundle/Resources/config/doctrine/Client.orm.xml&quot; in /opt/git/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
PHP message: PHP Fatal error:  Uncaught Doctrine\Common\Persistence\Mapping\MappingException: Invalid mapping file 'FOS.OAuthServerBundle.Entity.Client.orm.xml' for class 'FOS\OAuthServerBundle\Entity\Client'. in /opt/git/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:86
Stack trace:
#0 /opt/git/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php(117): Doctrine\Common\Persistence\Mapping\MappingException::invalidMappingFile('FOS\\OAuthServer...', 'FOS.OAuthServer...')
#1 /opt/git/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php(58): Doctrine\Common\Persistence\Mapping\Driver\FileDriver->getElement('FOS\\OAuthServer...')
#2 /opt/git/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(102): Doctrine\ORM\Mapping\Driver\XmlDriver->loadMetadataForClass('FOS\\OAuthServer...', Object(Doctrine\ORM\Mapping\ClassMetadata))
#3 /opt/git/wallabag/vendor/doc" while reading response header from upstream, client: 192.168.178.20, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "raspi3:9445"
```

#### vhost
```
[...]
root /var/www/html/wallabag/web;
#index app.php;

error_log /var/log/nginx/wallabag_error.log;
access_log /var/log/nginx/wallabag_access.log;

location / {
  # try to serve file directly, fallback to app.php
  try_files $uri /app.php$is_args$args;
}

location ~ ^/app\.php(/|$) {
  fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
  fastcgi_split_path_info ^(.+\.php)(/.*)$;
  include fastcgi_params;
  # When you are using symlinks to link the document root to the
  # current version of your application, you should pass the real
  # application path instead of the path to the symlink to PHP
  # FPM.
  # Otherwise, PHP's OPcache may not properly detect changes to
  # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
  # for more information).
  fastcgi_param  SCRIPT_FILENAME  $realpath_root$fastcgi_script_name;
  fastcgi_param DOCUMENT_ROOT $realpath_root;
  # Prevents URIs that include the front controller. This will 404:
  # http://domain.tld/app.php/some-path
  # Remove the internal directive to allow URIs like this
  internal;
}

# return 404 for all other php files not matching the front controller
# this prevents access to other php files you don't want to be accessible.
location ~ \.php$ {
  return 404;
}
[...]
```

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.2
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): first-time install
* php version: 7.0.16-3
* OS: Rasbian Jessie (up-to-date)
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

#### Installed PHP packages:
```
php7.0-bcmath/testing,now 7.0.16-3 armhf
php7.0-cli/testing,now 7.0.16-3 armhf
php7.0-common/testing,now 7.0.16-3 armhf
php7.0-curl/testing,now 7.0.16-3 armhf
php7.0-fpm/testing,now 7.0.16-3 armhf
php7.0-gd/testing,now 7.0.16-3 armhf
php7.0-json/testing,now 7.0.16-3 armhf
php7.0-mbstring/testing,now 7.0.16-3 armhf
php7.0-mcrypt/testing,now 7.0.16-3 armhf
php7.0-mysql/testing,now 7.0.16-3 armhf
php7.0-opcache/testing,now 7.0.16-3 armhf
php7.0-readline/testing,now 7.0.16-3 armhf
php7.0-tidy/testing,now 7.0.16-3 armhf
php7.0-xml/testing,now 7.0.16-3 armhf
php7.0-zip/testing,now 7.0.16-3 armhf
```

### Steps to reproduce/test case

1. `git clone https://github.com/wallabag/wallabag.git`
1. `cd wallabag && make install`
1. Symlink Wallabag directory to /var/www/html/
1. `chown -R www-data:www-data /opt/git/wallabag`
1. Set up Nginx vhost (see above)
1. Restart Nginx

**Comment by j0k3r** [comment]
The workaround is in the doc http://doc.wallabag.org/en/master/user/faq.html#i-ve-got-the-failed-to-load-external-entity-error-when-i-try-to-install-wallabag
