### ISSUE TITLE
Blank page after fresh install

### ISSUE THREAD

**Issue by olivyeah** [wallabag/wallabag#3366]
### Issue details
Hi,

I'll install wallabag following this page https://blog.arnaudminable.net/un-salon-de-lecture-dedans-ton-internet-avec-wallabag/  All is done but when i try to connect to my instance i have a blank page. The login window does't appear.
I check my error log, i have this 
#4 /mnt/www/wallabag/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\FingersCrossedHandler->handle(Array)
#5 /mnt/www/wallabag/vendor/" while reading response header from upstream, client: 193.55.147.18, server: wallabag.perpinux.org, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "wallabag.perpinux.org"
2017/10/03 06:52:46 [error] 11414#11414: *61 FastCGI sent in stderr: "PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/mnt/www/wallabag/vendor/friendsofsymfony/oauth-server-bundle/Resources/config/doctrine/Client.orm.xml&quot; in /mnt/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
PHP message: PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/mnt/www/wallabag/vendor/friendsofsymfony/oauth-server-bundle/Resources/config/doctrine/Client.orm.xml&quot; in /mnt/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php on line 814
PHP message: PHP Fatal error:  Uncaught Doctrine\Common\Persistence\Mapping\MappingException: Invalid mapping file 'FOS.OAuthServerBundle.Entity.Client.orm.xml' for class 'FOS\OAuthServerBundle\Entity\Client'. in /mnt/www/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:86
Stack trace:
#0 /mnt/www/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php(117): Doctrine\Common\Persistence\Mapping\MappingException::invalidMappingFile('FOS\\OAuthServer...', 'FOS.OAuthServer...')
#1 /mnt/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php(58): Doctrine\Common\Persistence\Mapping\Driver\FileDriver->getElement('FOS\\OAuthServer...')
#2 /mnt/www/wallabag/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(102): Doctrine\ORM\Mapping\Driver\XmlDriver->loadMetadataForClass('FOS\\OAuthServer...', Object(Doctrine\ORM\Mapping\ClassMetadata))
#3 /mnt/www/wallabag/vendor/doc" while reading response header from upstream, client: 193.55.147.18, server: wallabag.perpinux.org, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "wallabag.perpinux.org"

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* wallaba is installed via git clone 
* php version: 7
* OS: Debian 9
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MariaDB

### Steps to reproduce/test case

https://blog.arnaudminable.net/un-salon-de-lecture-dedans-ton-internet-avec-wallabag/
Thank you

**Comment by olivyeah** [comment]
I finally find the answer here https://doc.wallabag.org/en/user/faq.html#ive-got-the-failed-to-load-external-entity-error-when-i-try-to-install-wallabag
