### ISSUE TITLE
Fresh Install 500 Error

### ISSUE THREAD

**Issue by theced7** [wallabag/wallabag#3537]
### Environment

* wallabag version (or git revision) that exhibits the issue: latest
* How did you install wallabag? Via `git clone` or by downloading the package? `git clone`
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: PHP 7.0.19-1
* OS: Raspian 9.3
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): Postgres

### Steps to reproduce/test case
Cloned the repo, `make install`, copied wallabag folder into Apache Document root, assigned privileges according to documentation, modified virtual host:

```
root@raspberrypi:/etc/apache2/sites-enabled# cat 000-default.conf
<VirtualHost *:80>
#    ServerName domain.tld
#    ServerAlias www.domain.tld

    DocumentRoot /var/www/html/wallabag/web
    <Directory /var/www/html/wallabag/web>
        AllowOverride None
        Order Allow,Deny
        Allow from All
        Require all granted

        <IfModule mod_rewrite.c>
            Options -MultiViews
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^(.*)$ app.php [QSA,L]
        </IfModule>
    </Directory>

    # uncomment the following lines if you install assets as symlinks
    # or run into problems when compiling LESS/Sass/CoffeScript assets
    # <Directory /var/www/wallabag>
    #     Options FollowSymlinks
    # </Directory>

    # optionally disable the RewriteEngine for the asset directories
    # which will allow apache to simply reply with a 404 when files are
    # not found instead of passing the request into the full symfony stack
    <Directory /var/www/html/wallabag/web/bundles>
        <IfModule mod_rewrite.c>
            RewriteEngine Off
        </IfModule>
    </Directory>
    ErrorLog /var/log/apache2/wallabag_error.log
    CustomLog /var/log/apache2/wallabag_access.log combined
</VirtualHost>
root@raspberrypi:/etc/apache2/sites-enabled#
```

I only get an 500 error and this:

```
tail wallabag_error.log
[Wed Dec 27 20:53:47.427385 2017] [:error] [pid 32492] [client 192.168.178.39:62489] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException: Attempted to call function "token_get_all" from namespace "Doctrine\\Common\\Annotations". in /var/www/html/wallabag/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/TokenParser.php:56\nStack trace:\n#0 /var/www/html/wallabag/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/PhpParser.php(57): Doctrine\\Common\\Annotations\\TokenParser->__construct('<?php namespace...')\n#1 /var/www/html/wallabag/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(415): Doctrine\\Common\\Annotations\\PhpParser->parseClass(Object(ReflectionClass))\n#2 /var/www/html/wallabag/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(334): Doctrine\\Common\\Annotations\\AnnotationReader->collectParsingMetadata(Object(ReflectionClass))\n#3 /var/www/html/wallabag/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(214): Doctrine\\Common\\Annotations\\AnnotationReader->getClassImpo in /var/www/html/wallabag/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/TokenParser.php on line 56
root@raspberrypi:/var/log/apache2#
```

**Comment by Pitstopper** [comment]
Hi! Why do you use a triple nesting of directories in 'www' folder? I mean '/var/www/html/wallabag/web' - 
in my opinion 'html' folder is an unnecessary nesting. Му DocumentRoot is /var/www/wallabag/ and it's work fine.

I had a similar error due to incorrect access rights to internal folders. I fixed it this [way](https://doc.wallabag.org/en/admin/installation/rightaccess.html):
```
chown -R www-data:www-data /var/www/wallabag/var
chown -R www-data:www-data /var/www/wallabag/bin
chown -R www-data:www-data /var/www/wallabag/app/config
chown -R www-data:www-data /var/www/wallabag/vendor
chown -R www-data:www-data /var/www/wallabag/data/
```
But you wrote that you have everything with permissions on folders.

**Comment by j0k3r** [comment]
I guess the tokenizer function are disabled.
https://www.php.net/manual/en/tokenizer.installation.php

**Comment by thilinah** [comment]
This could happen if you are trying to run a Symfony app in an environment where `php7-tokenizer` is not installed. Happened to me when I tried to run a Symfony app on a docker container based on alpine.
