### ISSUE TITLE
Upgrade to wallabag 2.3.1 from 2.3 : PHP Fatal error

### ISSUE THREAD

**Issue by siSSSou** [wallabag/wallabag#3543]
### Issue details
I get a white page after an upgrade to 2.3.1 via command "make update".
```
2017/12/30 23:33:52 [error] 29972#29972: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: The directory "/var/www/wallabag/var/cache/prod/jms_serializer" is not writable. in /var/www/wallabag/vendor/jms/metadata/src/Metadata/Cache/FileCache.php:17
Stack trace:
#0 /var/www/wallabag/var/cache/prod/appProdProjectContainer.php(7210): Metadata\Cache\FileCache->__construct('/var/www/wallab...')
#1 /var/www/wallabag/var/cache/prod/appProdProjectContainer.php(3977): appProdProjectContainer->getJmsSerializer_MetadataFactoryService()
#2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(329): appProdProjectContainer->getNelmioApiDoc_Parser_JmsMetadataParserService()
#3 /var/www/wallabag/var/cache/prod/appProdProjectContainer.php(3862): Symfony\Component\DependencyInjection\Container->get('nelmio_api_doc....')
#4 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(329): appProdProjectContainer->getNelmioApiDoc_Extractor_ApiDocExtractorService()
#5 /v", client: 192.168.1.254, server: wallabag.*****.fr, request: "GET / HTTP/2.0", host: "wallabag.*****.fr"
```
The directory /var/www/wallabag/var/cache/prod/jms_serializer is writable though : 777 & owned by www-data (debian 9 & nginx)

### Environment

* wallabag version (or git revision) that exhibits the issue : 2.3.1
* Last wallabag version that did not exhibit the issue (if applicable) : previous version 2.3
* php version: 7.0
* OS : debian 9
* type of hosting (shared or dedicated) : dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL) : MariaDB

### Steps to reproduce/test case
Upgrade wallabag to 2.3.1

**Comment by Kdecherf** [comment]
Can you provide the result of the following command please?

```
ls -ld /var/www/wallabag/{,var/{,cache/{,prod/{,jms_serializer}}}} 
```
