### ISSUE TITLE
Shared Hosting installation failed, empty database

### ISSUE THREAD

**Issue by mbirth** [wallabag/wallabag#4046]
### Issue details

Similar problem as #3584 . Followed the [instructions for installation on shared web hosting](https://doc.wallabag.org/en/admin/installation/installation.html#on-shared-hosting), set database to SQLite and the file also gets created (with 0 Bytes), but it seems there's a step missing where I initialise the database.

Apache error log:

```
[Fri Jul 05 11:38:36 2019] [warn] [client 145.243.194.210] mod_fcgid: stderr: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: craue_config_setting in /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77
[Fri Jul 05 11:38:36 2019] [warn] [client 145.243.194.210] mod_fcgid: stderr: Stack trace:
[Fri Jul 05 11:38:36 2019] [warn] [client 145.243.194.210] mod_fcgid: stderr: #0 /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(77): PDO->prepare('SELECT t0.secti...', Array)
[Fri Jul 05 11:38:36 2019] [warn] [client 145.243.194.210] mod_fcgid: stderr: #1 /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(844): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('SELECT t0.secti...')
[Fri Jul 05 11:38:36 2019] [warn] [client 145.243.194.210] mod_fcgid: stderr: #2 /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(712): Doctrine\\DBAL\\Connection->executeQuery('SELECT t0.secti...', Array, Array)
[Fri Jul 05 11:38:36 2019] [warn] [client 145.243.194.210] mod_fcgid: stderr: #3 /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(196): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)
[Fri Jul 05 11:38:36 2019] [warn] [client 145.243.194.210] mod_fcgid: stderr: #4 /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/c in /var/www/virtual/mbirth/apps/wallabag-2.3.8/src/Wallabag/CoreBundle/Resources/views/base.html.twig on line 74
```

`bin/console` also doesn't work as it's missing the sensio/generator-bundle:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Did you forget a "use" statement for another namespace? in /var/www/virtual/mbirth/apps/wallabag-2.3.8/app/AppKernel.php:49
Stack trace:
#0 /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(448): AppKernel->registerBundles()
#1 /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(60): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/virtual/mbirth/apps/wallabag-2.3.8/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(122): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\A in /var/www/virtual/mbirth/apps/wallabag-2.3.8/app/AppKernel.php on line 49
```

### Environment

* wallabag version (or git revision) that exhibits the issue: `latest-v2-package` as of today, which turned out to be 2.3.8
* How did you install wallabag? Via `git clone` or by downloading the package? Package
* Last wallabag version that did not exhibit the issue (if applicable): n/a
* php version: 7.2.19
* OS: CentOS 6.10
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

1. Download/unpack package
2. Modify parameters.yml to use SQLite
3. Configure VHost
4. Open https://my.url/
5. Get HTTP 500 answer

**Comment by j0k3r** [comment]
If you don't specify the environment, it'll require that missing bundle because the default env is dev.

Run it with prod will fix that issue: `php bin/console --env=pord`.
Once installed you must run `php bin/console wallabag:install --env=prod`

**Comment by mbirth** [comment]
Awesome! That did the trick. Thanks!
