### ISSUE TITLE
Cannot install wallbag on debian VPS

### ISSUE THREAD

**Issue by PrzemekSkw** [wallabag/wallabag#4078]
### Issue details
I try to install wallbag on my VPS debian 9 server.
First I install deps:
```
sudo apt-get install apache2 libapache2-mod-php php composer git-core php-bcmath php-gd php-dompdf php-json php-mbstring php-xml php-tidy php-symfony-polyfill-iconv php-curl php-gettext php-bcmath php-mysql make zip unzip
```
Next:
```
cd /var/www/
/var/www# git clone https://github.com/wallabag/wallabag.git
/var/www# cd wallabag/
/var/www/wallabag# make install
```
and that error occur:
```
/var/www/wallabag$ sudo make install
[sudo] password for xxxx: 
Do not run this script as root!
Use --ignore-root-warning to ignore this error.
GNUmakefile:14: recipe for target 'install' failed
make: *** [install] Error 1
```
or without `sudo`
```
/var/www/wallabag$ make install
composer.phar not found, we'll see if composer is installed globally.
fatal: Unable to create '/var/www/wallabag/.git/index.lock': Permission denied
Loading composer repositories with package information
Installing dependencies from lock file

                                                                     
  [RuntimeException]                                                 
  /var/www/wallabag/vendor does not exist and could not be created.  
                                                                     

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

PHP Warning:  require(/var/www/wallabag/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/wallabag/bin/console on line 15
PHP Fatal error:  require(): Failed opening required '/var/www/wallabag/bin/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/wallabag/bin/console on line 15
GNUmakefile:14: recipe for target 'install' failed
make: *** [install] Error 255

```
### Environment

* wallabag version (or git revision) that exhibits the issue: last
* How did you install wallabag? Via `git clone` or by downloading the package? git clone
* Last wallabag version that did not exhibit the issue (if applicable): 
* php version: PHP Version => 7.0.33-0+deb9u3
* OS: Debian 9, `uname -a
Linux ArubaVPN 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU/Linux`
* type of hosting (shared or dedicated): VPS

I block login as root on my server, just login as normal user and use sudo.
I'm not experienced in servers just install openvpn on that server first time.

Regards,
Przemek

**Comment by j0k3r** [comment]
Just read the error:
> fatal: Unable to create '/var/www/wallabag/.git/index.lock': Permission denied

And then read the doc: https://doc.wallabag.org/en/admin/installation/rightaccess.html

**Comment by PrzemekSkw** [comment]
> Just read the error:
> 
> > fatal: Unable to create '/var/www/wallabag/.git/index.lock': Permission denied
> 
> And then read the doc: https://doc.wallabag.org/en/admin/installation/rightaccess.html

I give permissions to:
```
sudo chown -R www-data:www-data /var/www/wallabag/var
[sudo] password for xxxx: 
$ sudo chown -R www-data:www-data /var/www/wallabag/bin
$ sudo chown -R www-data:www-data /var/www/wallabag/app/config
$ sudo chown -R www-data:www-data /var/www/wallabag/vendor
chown: cannot access '/var/www/wallabag/vendor': No such file or directory
$ sudo chown -R www-data:www-data /var/www/wallabag/data/
$ sudo chown -R www-data:www-data /var/www/wallabag/web/
$ sudo chown -R www-data:www-data /var/www/wallabag/
```
but doesn't help. The same error.

**Comment by j0k3r** [comment]
What about :
> /var/www/wallabag/vendor does not exist and could not be created.  

Still have that issue?

Could you do:
- `whoami`
- `ls -lah /var/www/wallabag/`

**Comment by PrzemekSkw** [comment]
> Could you do:
> 
> * `whoami`
> * `ls -lah /var/www/wallabag/`

`whoami` gives my username

```
ls -lah /var/www/wallabag/
total 892K
drwxr-xr-x 13 www-data www-data 4.0K Aug  1 12:14 .
drwxr-xr-x  4 root     root     4.0K Aug  1 12:13 ..
drwxr-xr-x  5 www-data www-data 4.0K Aug  1 12:14 app
-rw-r--r--  1 www-data www-data   63 Aug  1 12:14 .babelrc
drwxr-xr-x  2 www-data www-data 4.0K Aug  1 12:14 bin
-rw-r--r--  1 www-data www-data  468 Aug  1 12:14 Capfile
-rw-r--r--  1 www-data www-data  61K Aug  1 12:14 CHANGELOG.md
-rw-r--r--  1 www-data www-data  271 Aug  1 12:14 .composer-auth.json
-rw-r--r--  1 www-data www-data 5.8K Aug  1 12:14 composer.json
-rw-r--r--  1 www-data www-data 397K Aug  1 12:14 composer.lock
-rw-r--r--  1 www-data www-data 1.1K Aug  1 12:14 COPYING.md
-rw-r--r--  1 www-data www-data  282 Aug  1 12:14 CREDITS.md
drwxr-xr-x  3 www-data www-data 4.0K Aug  1 12:14 data
drwxr-xr-x  6 www-data www-data 4.0K Aug  1 12:14 docker
-rw-r--r--  1 www-data www-data 1.6K Aug  1 12:14 docker-compose.yml
-rw-r--r--  1 www-data www-data  264 Aug  1 12:14 .editorconfig
-rw-r--r--  1 www-data www-data  336 Aug  1 12:14 .eslintrc.json
-rw-r--r--  1 www-data www-data  160 Aug  1 12:14 Gemfile
-rw-r--r--  1 www-data www-data  777 Aug  1 12:14 Gemfile.lock
drwxr-xr-x  8 www-data www-data 4.0K Aug  1 12:14 .git
drwxr-xr-x  2 www-data www-data 4.0K Aug  1 12:14 .github
-rw-r--r--  1 www-data www-data  905 Aug  1 12:14 .gitignore
-rwxr-xr-x  1 www-data www-data 1.6K Aug  1 12:14 GNUmakefile
-rw-r--r--  1 www-data www-data   20 Aug  1 12:14 Makefile
-rw-r--r--  1 www-data www-data 2.4K Aug  1 12:14 package.json
-rw-r--r--  1 www-data www-data 1.3K Aug  1 12:14 .php_cs
-rw-r--r--  1 www-data www-data  545 Aug  1 12:14 phpstan.neon
-rw-r--r--  1 www-data www-data 1.2K Aug  1 12:14 phpunit.xml.dist
-rw-r--r--  1 www-data www-data  102 Aug  1 12:14 postcss.config.js
-rw-r--r--  1 www-data www-data 1.9K Aug  1 12:14 README.md
-rw-r--r--  1 www-data www-data 2.2K Aug  1 12:14 RELEASE_PROCESS.md
drwxr-xr-x  2 www-data www-data 4.0K Aug  1 12:14 scripts
-rw-r--r--  1 www-data www-data 1015 Aug  1 12:14 .scrutinizer.yml
drwxr-xr-x  3 www-data www-data 4.0K Aug  1 12:14 src
-rw-r--r--  1 www-data www-data   45 Aug  1 12:14 .stylelintrc
drwxr-xr-x  3 www-data www-data 4.0K Aug  1 12:14 tests
-rw-r--r--  1 www-data www-data 2.4K Aug  1 12:14 .travis.yml
drwxr-xr-x  5 www-data www-data 4.0K Aug  1 12:14 var
drwxr-xr-x  7 www-data www-data 4.0K Aug  1 12:14 web
-rw-r--r--  1 www-data www-data  208 Aug  1 12:14 webpack.config.js
-rw-r--r--  1 www-data www-data 271K Aug  1 12:14 yarn.lock
```

**Comment by j0k3r** [comment]
I guess your "username" isn't part of the `www-data` group which means it can't create a folder inside the directory.

**Comment by PrzemekSkw** [comment]
> I guess your "username" isn't part of the `www-data` group which means it can't create a folder inside the directory.

I add my user to www-data group and still the same error.
```
/var/www/wallabag$ groups przemko
przemko : przemko sudo www-data
```

**Comment by j0k3r** [comment]
What is the same error?

**Comment by PrzemekSkw** [comment]
> What is the same error?

```
/var/www/wallabag$ make install
composer.phar not found, we'll see if composer is installed globally.
fatal: Unable to create '/var/www/wallabag/.git/index.lock': Permission denied
Loading composer repositories with package information
Installing dependencies from lock file

                                                                     
  [RuntimeException]                                                 
  /var/www/wallabag/vendor does not exist and could not be created.  
                                                                     

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

PHP Warning:  require(/var/www/wallabag/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/wallabag/bin/console on line 15
PHP Fatal error:  require(): Failed opening required '/var/www/wallabag/bin/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/wallabag/bin/console on line 15
GNUmakefile:14: recipe for target 'install' failed
make: *** [install] Error 255

```

**Comment by j0k3r** [comment]
There is still that issue
> fatal: Unable to create '/var/www/wallabag/.git/index.lock': Permission denied

Also, try:
```
SYMFONY_ENV=prod composer install -o --no-dev -vvv
```

**Comment by PrzemekSkw** [comment]
```
przemko@ArubaVPN:/var/www/wallabag$ sudo mkdir vendor
przemko@ArubaVPN:/var/www/wallabag$ ls
app      CHANGELOG.md   COPYING.md  docker              Gemfile.lock  package.json      postcss.config.js   scripts  var     webpack.config.js
bin      composer.json  CREDITS.md  docker-compose.yml  GNUmakefile   phpstan.neon      README.md           src      vendor  yarn.lock
Capfile  composer.lock  data        Gemfile             Makefile      phpunit.xml.dist  RELEASE_PROCESS.md  tests    web
przemko@ArubaVPN:/var/www/wallabag$ sudo chown -R www-data:www-data /var/www/wallabag/vendor
przemko@ArubaVPN:/var/www/wallabag$ SYMFONY_ENV=prod composer install -o --no-dev -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/var/www/wallabag): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /home/przemko/.config/composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.2.2 (2016-11-03 17:43:15) with PHP 7.0.33-0+deb9u3 on Linux / 4.9.0-9-amd64
Reading ./composer.lock
Loading composer repositories with package information
Installing dependencies from lock file
Reading ./composer.lock
Resolving dependencies through SAT
Dependency resolution completed in 0.004 seconds
Analyzed 215 packages to resolve dependencies
Analyzed 686 rules to resolve dependencies

                                                                                               
  [RuntimeException]                                                                           
  /var/www/wallabag/vendor/ocramius/package-versions does not exist and could not be created.  
                                                                                               

Exception trace:
 () at /usr/share/php/Composer/Util/Filesystem.php:182
 Composer\Util\Filesystem->ensureDirectoryExists() at /usr/share/php/Composer/Downloader/DownloadManager.php:203
 Composer\Downloader\DownloadManager->download() at /usr/share/php/Composer/Installer/LibraryInstaller.php:186
 Composer\Installer\LibraryInstaller->installCode() at /usr/share/php/Composer/Installer/LibraryInstaller.php:90
 Composer\Installer\LibraryInstaller->install() at /usr/share/php/Composer/Installer/PluginInstaller.php:61
 Composer\Installer\PluginInstaller->install() at /usr/share/php/Composer/Installer/InstallationManager.php:173
 Composer\Installer\InstallationManager->install() at /usr/share/php/Composer/Installer/InstallationManager.php:160
 Composer\Installer\InstallationManager->execute() at /usr/share/php/Composer/Installer.php:543
 Composer\Installer->doInstall() at /usr/share/php/Composer/Installer.php:216
 Composer\Installer->run() at /usr/share/php/Composer/Command/InstallCommand.php:135
 Composer\Command\InstallCommand->execute() at /usr/share/php/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /usr/share/php/Symfony/Component/Console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at /usr/share/php/Symfony/Component/Console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /usr/share/php/Composer/Console/Application.php:231
 Composer\Console\Application->doRun() at /usr/share/php/Symfony/Component/Console/Application.php:123
 Symfony\Component\Console\Application->run() at /usr/share/php/Composer/Console/Application.php:104
 Composer\Console\Application->run() at /usr/bin/composer:44

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

przemko@ArubaVPN:/var/www/wallabag$ sudo SYMFONY_ENV=prod composer install -o --no-dev -vvv
[sudo] password for przemko: 
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/var/www/wallabag): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.2.2 (2016-11-03 17:43:15) with PHP 7.0.33-0+deb9u3 on Linux / 4.9.0-9-amd64
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Reading ./composer.lock
Loading composer repositories with package information
Installing dependencies from lock file
Reading ./composer.lock
Resolving dependencies through SAT
Dependency resolution completed in 0.002 seconds
Analyzed 215 packages to resolve dependencies
Analyzed 686 rules to resolve dependencies
  - Installing ocramius/package-versions (1.4.0)
Downloading https://api.github.com/repos/Ocramius/PackageVersions/zipball/a4d4b60d0e60da2487bd21a2c6ac089f85570dbb
    Downloading: 100%         
Writing /root/.composer/cache/files/ocramius/package-versions/9015316288b55423c693c083934dccb5ab72981d.zip into cache from /var/www/wallabag/vendor/ocramius/package-versions/6a321d0ec6a4cb5ffc6ec837abb551b7
    Extracting archive
Executing command (CWD): unzip '/var/www/wallabag/vendor/ocramius/package-versions/6a321d0ec6a4cb5ffc6ec837abb551b7' -d '/var/www/wallabag/vendor/composer/54dd5af2' && chmod -R u+w '/var/www/wallabag/vendor/composer/54dd5af2'

Loading plugin PackageVersions\Installer
PHP Fatal error:  Uncaught TypeError: Return value of PackageVersions\Installer::activate() must be an instance of PackageVersions\void, none returned in /var/www/wallabag/vendor/ocramius/package-versions/src/PackageVersions/Installer.php:80
Stack trace:
#0 /usr/share/php/Composer/Plugin/PluginManager.php(232): PackageVersions\Installer->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 /usr/share/php/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(PackageVersions\Installer))
#2 /usr/share/php/Composer/Installer/PluginInstaller.php(63): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#3 /usr/share/php/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#4 /usr/share/php/Composer/Installer/InstallationManager.php(160): Composer\Installer\InstallationManager->install(Object(Composer\R in /var/www/wallabag/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 80

Fatal error: Uncaught TypeError: Return value of PackageVersions\Installer::activate() must be an instance of PackageVersions\void, none returned in /var/www/wallabag/vendor/ocramius/package-versions/src/PackageVersions/Installer.php:80
Stack trace:
#0 /usr/share/php/Composer/Plugin/PluginManager.php(232): PackageVersions\Installer->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 /usr/share/php/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(PackageVersions\Installer))
#2 /usr/share/php/Composer/Installer/PluginInstaller.php(63): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#3 /usr/share/php/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#4 /usr/share/php/Composer/Installer/InstallationManager.php(160): Composer\Installer\InstallationManager->install(Object(Composer\R in /var/www/wallabag/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 80
przemko@ArubaVPN:/var/www/wallabag$ make install
composer.phar not found, we'll see if composer is installed globally.
fatal: Unable to create '/var/www/wallabag/.git/index.lock': Permission denied
Loading composer repositories with package information
Installing dependencies from lock file
  - Installing ocramius/package-versions (1.4.0)
    Failed to download ocramius/package-versions from dist: Could not delete /var/www/wallabag/vendor/ocramius/package-versions/infection.json.dist: 
    Now trying to download from source
  - Installing ocramius/package-versions (1.4.0)

                                                                                             
  [RuntimeException]                                                                         
  Could not delete /var/www/wallabag/vendor/ocramius/package-versions/infection.json.dist:   
                                                                                             

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

PHP Warning:  require(/var/www/wallabag/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/wallabag/bin/console on line 15
PHP Fatal error:  require(): Failed opening required '/var/www/wallabag/bin/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/wallabag/bin/console on line 15
GNUmakefile:14: recipe for target 'install' failed
make: *** [install] Error 255
przemko@ArubaVPN:/var/www/wallabag$ 

```

**Comment by j0k3r** [comment]
The main problem is here:

> przemko@ArubaVPN:/var/www/wallabag$ sudo mkdir vendor

You shouldn't have to `sudo` to create a folder if your user is in the same group as `www-data`.

I've no idea how to fix it.
Sorry.

**Comment by PrzemekSkw** [comment]
@j0k3r I cannot makedir without sudo `permission denied`.
Thanks for Your help and time.
Regards.

**Comment by virtadpt** [comment]
For what it's worth, it's easier to install Wallabag in your home directory and then point your web server at that directory.  That's what I did (Ubuntu 18.04 LTS) when I ran into this problem, and it's been working nicely ever since.

**Comment by bestinera** [comment]
I have same problem，but i find a new method to install.
You can try the following method
https://www.zjzj.xyz/archives/1403/
https://spiritx.xyz/993.html
![Lily_Screenshot_1573733876606e7.png](http://s3tu.com/images/2019/11/14/Lily_Screenshot_1573733876606e7.png)

**Comment by Epy** [comment]
> I have same problem，but i find a new method to install. You can try the following method 

This is a spammer don't click on links

**Comment by Kdecherf** [comment]
Closing this as it's 4 years-old
