### ISSUE TITLE
[2.4.0] Generated hashed urls issue

### ISSUE THREAD

**Issue by nsteinmetz** [wallabag/wallabag#4828]
### Issue details

After upgrading to 2.4.0 and migrating the db, when I generate the hashed urls, I got : 

```
/ # /var/www/wallabag/bin/console wallabag:generate-hashed-urls
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".
Did you forget a "use" statement for another namespace? in /var/www/wallabag/app/AppKernel.php:52
Stack trace:
#0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(493): AppKernel->registerBundles()
#1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/wallabag/bin/console(27): Symfony\Component\Conso in /var/www/wallabag/app/AppKernel.php on line 52
/ # /var/www/wallabag/bin/console wallabag
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".
Did you forget a "use" statement for another namespace? in /var/www/wallabag/app/AppKernel.php:52
Stack trace:
#0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(493): AppKernel->registerBundles()
#1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/wallabag/bin/console(27): Symfony\Component\Conso in /var/www/wallabag/app/AppKernel.php on line 52
/ # 
```

### Environment

* wallabag version 2.4.0 upgraded from 2.3.8
* Docker image
* php version: 7.3.25
* OS: Alpine 3.12
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): postgresql

### Steps to reproduce/test case

* Upgrade from 2.3.8 to 2.4.0
* run `/var/www/wallabag/bin/console doctrine:migration:migrate --env=prod --no-interaction` (docs needs to be updated by the way - it's no longer `doctrine:migrate`
* run `/var/www/wallabag/bin/console wallabag:generate-hashed-urls`

**Comment by nsteinmetz** [comment]
Ok, it requires a `--env=prod` to work.

But if you don't specify `env`, you fall into test or dev mode which has this issue for all (?) commands (like clear cache also)

**Comment by tcitworld** [comment]
That's because dev/test env requires dependencies that are not installed in prod environment.
