### ISSUE TITLE
Error on Android

### ISSUE THREAD

**Issue by cornetth** [wallabag/wallabag#4997]
### Environment

* **Version**: I'm using app.wallabag.it through the Android app ver. 2.4.2 (228)

<details>
  <summary>Every time I open the app I get this:</summary>

  ```
  Server error
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
Stacktrace:
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
	at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
	at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
	at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
	at wallabag.apiwrapper.WallabagService.lambda$modifyArticle$7$WallabagService(WallabagService.java:868)
	at wallabag.apiwrapper.-$$Lambda$WallabagService$zRXhJOiZErB9tSv-KfKfEd87v0w.run(Unknown Source:6)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:140)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:133)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:128)
	at wallabag.apiwrapper.WallabagService.modifyArticle(WallabagService.java:868)
	at wallabag.apiwrapper.ModifyArticleBuilder.execute(ModifyArticleBuilder.java:103)
	at wallabag.apiwrapper.ModifyArticleBuilder.execute(ModifyArticleBuilder.java:86)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncArticleChange(OfflineChangesSynchronizer.java:368)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncOfflineQueue(OfflineChangesSynchronizer.java:118)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.synchronize(OfflineChangesSynchronizer.java:68)
	at fr.gaulupeau.apps.Poche.service.tasks.SyncOfflineChangesTask.run(SyncOfflineChangesTask.java:17)
	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
	at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
	at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)

  ```
</details>

### What steps will reproduce the bug?

Just open my app on Android.

**Comment by j0k3r** [comment]
Shouldn't this be moved to wallabag/android-app instead?

**Comment by MFYDev** [comment]
Same here. I tried to find solutions in both android-app and here, but no one gave answers.
 
Really drives me nuts.

**Comment by petesimonic** [comment]
Hello! User with the same Android app version and build, and server 2.3.8~ynh3 get similar error from the app, and adding items via Share to Wallabag doesn't work anymore.

The error text is following.
> Server error
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
Stacktrace:
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
	at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
	at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
	at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
	at wallabag.apiwrapper.WallabagService.addArticle(WallabagService.java:236)
	at wallabag.apiwrapper.AddArticleBuilder.execute(AddArticleBuilder.java:73)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.addLink(OfflineChangesSynchronizer.java:252)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncOfflineQueue(OfflineChangesSynchronizer.java:146)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.synchronize(OfflineChangesSynchronizer.java:68)
	at fr.gaulupeau.apps.Poche.service.tasks.SyncOfflineChangesTask.run(SyncOfflineChangesTask.java:17)
	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
	at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
	at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)

**Comment by petesimonic** [comment]
Here I got a new error output from the same user when he tried new version (2.4.3). It can't download his articles from the server.

> Unknown error
> 
> java.io.InterruptedIOException
> 
> Stacktrace:
> 
> java.io.InterruptedIOException
> 
> 	at okhttp3.internal.http2.Http2Stream.waitForIo$okhttp(Http2Stream.kt:662)
> 
> 	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:378)
> 
> 	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
> 
> 	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
> 
> 	at okio.ForwardingSource.read(ForwardingSource.kt:29)
> 
> 	at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:288)
> 
> 	at okio.RealBufferedSource.indexOfElement(RealBufferedSource.kt:455)
> 
> 	at okio.RealBufferedSource.indexOfElement(RealBufferedSource.kt:124)
> 
> 	at com.squareup.moshi.JsonUtf8Reader.nextQuotedValue(JsonUtf8Reader.java:828)
> 
> 	at com.squareup.moshi.JsonUtf8Reader.nextString(JsonUtf8Reader.java:633)
> 
> 	at com.squareup.moshi.StandardJsonAdapters$10.fromJson(StandardJsonAdapters.java:215)
> 
> 	at com.squareup.moshi.StandardJsonAdapters$10.fromJson(StandardJsonAdapters.java:213)
> 
> 	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
> 
> 	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:194)
> 
> 	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:156)
> 
> 	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
> 
> 	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
> 
> 	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
> 
> 	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
> 
> 	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:194)
> 
> 	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:156)
> 
> 	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
> 
> 	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:194)
> 
> 	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:156)
> 
> 	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
> 
> 	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
> 
> 	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
> 
> 	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
> 
> 	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
> 
> 	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:104)
> 
> 	at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
> 
> 	at wallabag.apiwrapper.WallabagService.lambda$getArticles$0$WallabagService(WallabagService.java:218)
> 
> 	at wallabag.apiwrapper.-$$Lambda$WallabagService$PrzoUvX9wnRBX2jTxVqPJ-eD3zU.run(Unknown Source:4)
> 
> 	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:140)
> 
> 	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:133)
> 
> 	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:128)
> 
> 	at wallabag.apiwrapper.WallabagService.getArticles(WallabagService.java:218)
> 
> 	at wallabag.apiwrapper.ArticlesQueryBuilder.execute(ArticlesQueryBuilder.java:282)
> 
> 	at wallabag.apiwrapper.ArticlesPageIterator.hasNext(ArticlesPageIterator.java:80)
> 
> 	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.performUpdate(ArticleUpdater.java:183)
> 
> 	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.update(ArticleUpdater.java:127)
> 
> 	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.updateArticles(ArticleUpdateWorker.java:77)
> 
> 	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.update(ArticleUpdateWorker.java:37)
> 
> 	at fr.gaulupeau.apps.Poche.service.tasks.UpdateArticlesTask.run(UpdateArticlesTask.java:17)
> 
> 	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
> 
> 	at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
> 
> 	at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
> 
> 	at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
> 
> 	at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
> 
> 	at java.lang.Thread.run(Thread.java:923)

**Comment by nicosomb** [comment]
Duplicate of https://github.com/wallabag/android-app/issues/1247
