### ISSUE TITLE
Issue adding tag 'politics' to article on https://app.wallabag.it/

### ISSUE THREAD

**Issue by MagicAndi** [wallabag/wallabag#4998]
### Environment

The hosted Wallabag web application at https://app.wallabag.it/ (username MagicAndi)

* **Version**:       2.4.1-dev (from https://app.wallabag.it/about)
* **Installation**:
* **PHP version**:
* **OS**:
* **Database**:
* **Parameters**:

### What steps will reproduce the bug?

The issue occurs when I try and add the tag 'politics' (without quotes) to an article. When I add the tag to this article https://app.wallabag.it/view/12435410, and hit enter, the request appears to time out on this URL:

https://app.wallabag.it/new-tag/12435410

I can add other tags without any issue, but if I try and add a 'politics' to this or other articles, the attempt fails. If I add multiple tags at the same time, and include 'politics', it will fail. If I try to add the same tags without politics, it will successfully add the tags to the article. 

Can you help resolve this? The username of my subscription is MagicAndi. Thanks.

**Comment by cornetth** [comment]
I'm having a similar issue. My politics tag already exists. I can see it on the tags page. But when I try to add it to an article, I get exactly the same error.

**Comment by nicosomb** [comment]
```
[2021-02-02 09:13:59] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\OutOfMemoryException: "Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 790528 bytes)" at /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php
```

**Comment by nicosomb** [comment]
It seems to be related to https://github.com/wallabag/wallabag/issues/2865

**Comment by MagicAndi** [comment]
For now, I'll work round it by creating a 'politics2' tag, and then using a script to bulk re-assign to the 'politics' tag if/when this issue is fixed.

**Comment by derekmahar** [comment]
Might this be the cause of the following error that I have encountered recently in Wallabag for Android?  I noticed that Wallabag would report this error each time I added tags to an article, but it didn't occur to me that it might be due to a particular tag like "politics".

```
Server error
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500
Stacktrace:
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500
at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
at wallabag.apiwrapper.WallabagService.lambda$modifyArticle$7$WallabagService(WallabagService.java:868)
at wallabag.apiwrapper.-$$Lambda$WallabagService$zRXhJOiZErB9tSv-KfKfEd87v0w.run(Unknown Source:6)
at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:140)
at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:133)
at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:128)
at wallabag.apiwrapper.WallabagService.modifyArticle(WallabagService.java:868)
at wallabag.apiwrapper.ModifyArticleBuilder.execute(ModifyArticleBuilder.java:103)
at wallabag.apiwrapper.ModifyArticleBuilder.execute(ModifyArticleBuilder.java:86)
at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncArticleChange(OfflineChangesSynchronizer.java:368)
at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncOfflineQueue(OfflineChangesSynchronizer.java:118)
at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.synchronize(OfflineChangesSynchronizer.java:68)
at fr.gaulupeau.apps.Poche.service.tasks.SyncOfflineChangesTask.run(SyncOfflineChangesTask.java:17)
at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
at java.lang.Thread.run(Thread.java:919)
```

**Comment by derekmahar** [comment]
Note that when I add tag "politics" to an article using the Web client, it times out on URL https://app.wallabag.it/new-tag/12561633.

**Comment by derekmahar** [comment]
I just verified that this error occurs when I add tag "politics", but not tag "politics2".

> Might this be the cause of the following error that I have encountered recently in Wallabag for Android? I noticed that Wallabag would report this error each time I added tags to an article, but it didn't occur to me that it might be due to a particular tag like "politics".
> 
> ```
> Server error
> wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500
> Stacktrace:
> wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500
> at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
> at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
> at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
> at wallabag.apiwrapper.WallabagService.lambda$modifyArticle$7$WallabagService(WallabagService.java:868)
> at wallabag.apiwrapper.-$$Lambda$WallabagService$zRXhJOiZErB9tSv-KfKfEd87v0w.run(Unknown Source:6)
> at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:140)
> at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:133)
> at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:128)
> at wallabag.apiwrapper.WallabagService.modifyArticle(WallabagService.java:868)
> at wallabag.apiwrapper.ModifyArticleBuilder.execute(ModifyArticleBuilder.java:103)
> at wallabag.apiwrapper.ModifyArticleBuilder.execute(ModifyArticleBuilder.java:86)
> at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncArticleChange(OfflineChangesSynchronizer.java:368)
> at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncOfflineQueue(OfflineChangesSynchronizer.java:118)
> at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.synchronize(OfflineChangesSynchronizer.java:68)
> at fr.gaulupeau.apps.Poche.service.tasks.SyncOfflineChangesTask.run(SyncOfflineChangesTask.java:17)
> at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
> at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
> at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
> at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
> at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
> at java.lang.Thread.run(Thread.java:919)
> ```

**Comment by MagicAndi** [comment]
OK, I've discovered an additional tag that causes the same issue: 'science'. This results in the same error as previously described.

Given that the 2 tags that we know of ('science' and 'politics') that cause this issue are (I'm assuming) popular tags, are we hitting a database constraint for the tags, or is this simply a PHP memory issue as suggested by the error message @nicosomb posted? Thanks.

**Comment by MagicAndi** [comment]
And another tag causing the same issue: 'blog'

**Comment by MagicAndi** [comment]
Just around this issue - I noticed an outage the other day just as I discovered the 'science' tag, and again just now as I did some further testing on the 'blog' tag. Is there a link between this issue and the '504 Gateway Time-out' error that we're seeing during the recent outages, or is it simply coincidence? Thanks.

**Comment by MagicAndi** [comment]
And another tag: 'science', on this article: https://app.wallabag.it/view/12641615

**Comment by derekmahar** [comment]
@MagicAndi 
```
403: Forbidden
You can not access this entry.
```

**Comment by MagicAndi** [comment]
@derekmahar Apologies, it is an article in my subscription, I only included it to help the site admins when searching the logs. You can view the shared article here:

https://app.wallabag.it/share/60338380f2e090.11205916

**Comment by MagicAndi** [comment]
I did some analysis on the tags used in my subscription, as I wasn't sure if the issue was limited to the tags within my subscription (i.e. the tags I most commonly used caused this problem), or if it was an aggregrate issue across all the subscriptions. Based on what I found, it appears to be the latter. I ran a quick script to count how often different tags are used in my subscription (4391 unique tags across 4064 articles), and the top 10 tags are:

Tag   				|  Count
------------------------------
programming 		| 594
politics 			| 427
career 				| 295
webdev 				| 211
higher education 	| 203
security 			| 201
coronavirus 		| 190
productivity 		| 179
covid-19 			| 167
technology 			| 162

The tags that I have discovered so far that cause this issue ('science', 'blog' and 'politics') aren't in my top 10 (indeed, I have never used the tag 'blog' before).

**Comment by nicosomb** [comment]
In fact, tags are not "user related": the "politics" tag is the same for all the users in the database ...

**Comment by MagicAndi** [comment]
Which is the point I was making in my comment above.

**Comment by derekmahar** [comment]
> ```
> [2021-02-02 09:13:59] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\OutOfMemoryException: "Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 790528 bytes)" at /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php
> ```

Why does Wallabag exhaust its memory when adding a tag to its database?  When adding a tag, does Wallabag perform a query that retrieves all articles that have this tag?  Why does it perform this query when it should only have to update the database?

**Comment by derekmahar** [comment]
I just encountered the error with tag "psychology".

Summary of failing tags:

- blog
- politics
- psychology
- science

**Comment by nicosomb** [comment]
Hello there!
I just tried a quick fix on app.wallabag.it: could you please try it? :)

**Comment by MagicAndi** [comment]
I can confirm that I can add the tags 'politics' and 'science' now without any issue. Thanks for your help with this.

**Comment by MagicAndi** [comment]
OK, this issue appears to be back. When I attempt to add the tag 'linux' to an article, I get the following error message (see attached screenshot):

500 Internal Server Error 
Error: Allowed memory size of 1073741824 bytes exhausted  (tried to allocate 2557448 bytes)

![WallabagError](https://user-images.githubusercontent.com/5617999/114395358-c868c180-9b8b-11eb-981c-a76764f26c23.jpg)

When I checked the current master branch of the Wallabag code, there appears to have been a regression. The code at line 715 has been re-added, despite being removed in the previous applied commit: 

https://github.com/wallabag/wallabag/commit/2e4d4f353147a25c8e31301e2e6d6de2ae15745d

Can we get this fix re-applied? Thanks.

**Comment by nicosomb** [comment]
Oops, sorry, I made a mistake. Could you try again?

**Comment by MagicAndi** [comment]
Tried again adding the tag, now working correctly. Thanks.

**Comment by nicosomb** [comment]
This bug still occurs. I reopen it.
