### ISSUE TITLE
Unable to open primary script: /usr/share/webapps/wallabag/app.php

### ISSUE THREAD

**Issue by starsareintherose** [wallabag/wallabag#5354]
### Environment

* **Version**:     latest
* **Installation**: AUR
* **PHP version**:  7.4 latest
* **OS**:           ArchLinux
* **Database**:     sqlite3 latest

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
  PASTE HERE
  ```
</details>

### What steps will reproduce the bug?

```
[root@archlinux nginx]# cat wallabag_access.log
120.77.245.50 - - [25/Jul/2021:20:48:02 +0800] "GET / HTTP/1.1" 404 36 "-" "curl/7.78.0"
120.192.37.36 - - [25/Jul/2021:21:43:41 +0800] "GET / HTTP/2.0" 404 25 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4571.0 Safari/537.36 Edg/93.0.957.0"
[root@archlinux nginx]# cat wallabag_error.log
2021/07/25 20:48:02 [error] 7064#7064: 32 FastCGI sent in stderr: "Unable to open primary script: /usr/share/webapps/wallabag/app.php (No such file or directory)" while reading response header from upstream, client: 120.77.245.50, server: read.malacology.net, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php74-fpm/php-fpm.sock:", host: "read.malacology.net"
2021/07/25 21:43:41 [error] 9868#9868: 3 FastCGI sent in stderr: "Unable to open primary script: /usr/share/webapps/wallabag/app.php (No such file or directory)" while reading response header from upstream, client: 120.192.37.36, server: read.malacology.net, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php74-fpm/php-fpm.sock:", host: "read.malacology.net"
```
Actually, there is no app.php
```
[root@archlinux ~]# cd /usr/share/webapps/wallabag
[root@archlinux wallabag]# ls -o
total 936
drwxr-xr-x 5 root 4096 Jul 24 00:46 app
drwxr-xr-x 2 root 4096 Jul 24 00:46 bin
-rwxr-xr-x 1 root 72485 Jul 24 00:46 CHANGELOG.md
-rwxr-xr-x 1 root 3350 Jul 24 00:46 CODE_OF_CONDUCT.md
-rwxr-xr-x 1 root 5717 Jul 24 00:46 composer.json
-rwxr-xr-x 1 root 474281 Jul 24 00:46 composer.lock
-rwxr-xr-x 1 root 1069 Jul 24 00:46 COPYING.md
-rwxr-xr-x 1 root 282 Jul 24 00:46 CREDITS.md
lrwxrwxrwx 1 root 22 Jul 24 00:46 data -> /var/lib/wallabag/data
drwxr-xr-x 6 root 4096 Jul 24 00:46 docker
-rwxr-xr-x 1 root 1585 Jul 24 00:46 docker-compose.yml
-rwxr-xr-x 1 root 1781 Jul 24 00:46 GNUmakefile
-rwxr-xr-x 1 root 20 Jul 24 00:46 Makefile
-rwxr-xr-x 1 root 2417 Jul 24 00:46 package.json
-rwxr-xr-x 1 root 311 Jul 24 00:46 phpstan.neon
-rwxr-xr-x 1 root 1151 Jul 24 00:46 phpunit.xml.dist
-rwxr-xr-x 1 root 2395 Jul 24 00:46 README.md
-rwxr-xr-x 1 root 1750 Jul 24 00:46 RELEASE_PROCESS.md
drwxr-xr-x 2 root 4096 Jul 24 00:46 scripts
drwxr-xr-x 3 root 4096 Jul 24 00:46 src
drwxr-xr-x 3 root 4096 Jul 24 00:46 tests
lrwxrwxrwx 1 root 21 Jul 24 00:46 var -> /var/lib/wallabag/var
drwxr-xr-x 67 root 4096 Jul 24 00:47 vendor
drwxr-xr-x 8 root 4096 Jul 24 00:47 web
-rwxr-xr-x 1 root 216 Jul 24 00:46 webpack.config.js
-rwxr-xr-x 1 root 316840 Jul 24 00:46 yarn.lock
[root@archlinux wallabag]# cd /var/lib/wallabag/data && ls -o
total 4
drwxr-xr-x 2 root 4096 Jul 24 00:47 db
[root@archlinux data]# cd /var/lib/wallabag/var && ls -o
total 80
-rw-r--r-- 1 root 42998 Jul 24 00:46 bootstrap.php.cache
-rw-r--r-- 1 root 33831 Jul 24 00:46 SymfonyRequirements.php
```
I just follow the official guide to configure the nginx
```
code]
[root@archlinux ~]# cd /etc/nginx/
[root@archlinux nginx]# cd sites-enabled
[root@archlinux sites-enabled]# cat read.conf
server {
            listen 80;
            server_name read.malacology.net;
            return 301 https://$server_name$request_uri;
}
server {
    listen 443 ssl http2;
    server_name read.malacology.net;
    root /usr/share/webapps/wallabag;
    ssl_certificate /etc/nginx/web_ssl/read/1_read.malacology.net_bundle.crt;
    ssl_certificate_key /etc/nginx/web_ssl/read/2_read.malacology.net.key;
    ssl_session_cache builtin:1000 shared:SSL:10m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;
    access_log /var/log/nginx/access.log;

    location / {
        # try to serve file directly, fallback to app.php
        try_files $uri /app.php$is_args$args;
    }
    location ~ ^/app\.php(/|$) {
        # if, for some reason, you are still using PHP 5,
        # then replace /run/php/php7.0 by /var/run/php5
        fastcgi_pass unix:/run/php74-fpm/php-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        # When you are using symlinks to link the document root to the
        # current version of your application, you should pass the real
        # application path instead of the path to the symlink to PHP
        # FPM.
        # Otherwise, PHP's OPcache may not properly detect changes to
        # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
        # for more information).
        fastcgi_param  SCRIPT_FILENAME  $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        # Prevents URIs that include the front controller. This will 404:
        # http://domain.tld/app.php/some-path
        # Remove the internal directive to allow URIs like this
        internal;
    }
    # return 404 for all other php files not matching the front controller
    # this prevents access to other php files you don't want to be accessible.
    location ~ \.php$ {
        return 404;
    }
}

```

**Comment by starsareintherose** [comment]
Now I change the root to `/usr/share/webapps/wallabag/web`, I can find an app.php, but it reports in error log
```
2021/07/25 23:19:10 [error] 15447#15447: *20 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught UnexpectedValueException: The stream or file "/var/lib/wallabag/var/logs/prod.log" could not be opened in append mode: failed to open stream: Permission denied in /usr/share/webapps/wallabag/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:110
Stack trace:

#0 /usr/share/webapps/wallabag/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write()

#1 /usr/share/webapps/wallabag/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php(59): Monolog\Handler\AbstractProcessingHandler->handle()

#2 /usr/share/webapps/wallabag/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php(92): Monolog\Handler\AbstractHandler->handleBatch()

#3 /usr/share/webapps/wallabag/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php(113): Monolog\Handler\FingersCrossedHandler->activate()

#4 /usr/share/webapps/wallabag/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handl" while reading response header from upstream, client: 120.192.37.36, server: read.malacology.net, req
```
