### ISSUE TITLE
Unable to import json, showing that 500: Internal Server Error

### ISSUE THREAD

**Issue by starsareintherose** [wallabag/wallabag#5390]
### Environment

\* \*\*Version\*\*:2.4.2  
\* \*\*Installation\*\*:AUR  
\* \*\*PHP version\*\*:7.4.21  
\* \*\*OS\*\*:ArchLinux  
\* \*\*Database\*\*:Mariadb  10.6.3  
\* \*\*Parameters\*\*:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>
```
parameters:  
   database\_driver: pdo\_mysql  
   database\_host: 127.0.0.1  
   database\_port: 3306  
   database\_name: wallabag  
   database\_user: wallabag  
   database\_password:   
   database\_path: /var/lib/mysql/wallabag  
   database\_table\_prefix: wallabag\_  
   database\_socket: null  
   database\_charset: utf8mb4  
   domain\_name: 'https://read.malacology.net'  
   server\_name: 'Your wallabag instance'  
   mailer\_transport: smtp  
   mailer\_user: null  
   mailer\_password: null  
   mailer\_host: 127.0.0.1  
   mailer\_port: false  
   mailer\_encryption: null  
   mailer\_auth\_mode: null  
   locale: en  
   secret: guoyiwang123  
   twofactor\_auth: true  
   twofactor\_sender: no-reply@wallabag.org  
   fosuser\_registration: true  
   fosuser\_confirmation: true  
   fos\_oauth\_server\_access\_token\_lifetime: 3600  
   fos\_oauth\_server\_refresh\_token\_lifetime: 1209600  
   from\_email: no-reply@wallabag.org  
   rss\_limit: 50  
   rabbitmq\_host: localhost  
   rabbitmq\_port: 5672  
   rabbitmq\_user: guest  
   rabbitmq\_password: guest  
   rabbitmq\_prefetch\_count: 10  
   redis\_scheme: tcp  
   redis\_host: localhost  
   redis\_port: 6379  
   redis\_path: null  
   redis\_password: null  
   sentry\_dsn: null  
```
</details>

### What steps will reproduce the bug?
The web shows when I try to import the json
```
500: Internal Server Error
Unable to write in the "/usr/share/webapps/wallabag/web/uploads/import" directory.
```
and nginx log shows that
```
2021/08/10 03:14:48 [error] 53746#53746: *1 FastCGI sent in stderr: "PHP message: PHP Warning: mkdir(): Permission denied in /usr/share/webapps/wallabag/vendor/friendsofsymfony/jsrouting-bundle/Extractor/ExposedRoutesExtractor.php on line 174" while reading response header from upstream, client: 47.241.99.23, server: read.malacology.net, request: "GET /js/routing?callback=fos.Router.setData HTTP/2.0", upstream: "fastcgi://unix:/run/php74-fpm/php-fpm.sock:", host: "read.malacology.net", referrer: "https://read.malacology.net/import/wallabag-v2"
````
If I make the `/usr/share/webapps/wallabag/web/uploads/import"` 777, it still doesn't work. Now all the files are 755, and the owner of wallabag files is http and running user is http.
When I import more than two, it shows
```
Compile Error: require(): Failed opening required '/var/lib/wallabag/var/cache/prod/rulerz/rulerz_executor_fcf8b5da' (include_path='.:')
```

**Comment by j0k3r** [comment]
Maybe https://doc.wallabag.org/en/admin/installation/rightaccess.html ?

**Comment by starsareintherose** [comment]
Not that issue, the documentation is too old, I PHP-fpm, nginx as root, also all the dir belong to root, absolutely not the right issue, but see the terrible code
```
░▒▓    /usr/share/webapps/wallabag  php7 bin/console make rn                                                              ✔  root@helix  14:08:12  ▓▒░
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".
Did you forget a "use" statement for another namespace? in /usr/share/webapps/wallabag/app/AppKernel.php:52
Stack trace:
#0 /usr/share/webapps/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(493): AppKernel->registerBundles()
#1 /usr/share/webapps/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /usr/share/webapps/wallabag/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
#3 /usr/share/webapps/wallabag/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#4 /usr/share/webapps/wallabag/bin/console(27): Symfony\Component\Console\Application->run()
#5 {main}
  thrown in /usr/share/webapps/wallabag/app/AppKernel.php on line 52

**Comment by j0k3r** [comment]
What are you trying to achieve with that command?

**Comment by starsareintherose** [comment]
test the environment

**Comment by starsareintherose** [comment]
like what rhw document said
