### ISSUE TITLE
API clients error on wallabag.it

### ISSUE THREAD

**Issue by FrapiFrance** [wallabag/wallabag#5460]
error on wallabag.it hosted wallabag.
### Environment

* **Version**: 2.4.2 according to https://app.wallabag.it/about
* **Installation**: wallabag.it
* **PHP version**: wallabag.it
* **OS**: wallabag.it
* **Database**: wallabag.it
* **Parameters**: 

### What steps will reproduce the bug?
From several clients (the standard Android client 2.4.3 (229), and plop-reader http://plop-reader.pascal-martin.fr/ ), even after rebuilding new Client ID
error 500 when trying to retrieve new articles or full resync

the "bag it!" bookmarklet still works.

Here is the stacktrace  (from android app) : 
```
Erreur serveur
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
Pile d'erreur :
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
 at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
 at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
 at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
 at wallabag.apiwrapper.WallabagService.addArticle(WallabagService.java:236)
 at wallabag.apiwrapper.AddArticleBuilder.execute(AddArticleBuilder.java:73)
 at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.addLink(OfflineChangesSynchronizer.java:252)
 at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncOfflineQueue(OfflineChangesSynchronizer.java:146)
 at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.synchronize(OfflineChangesSynchronizer.java:68)
 at fr.gaulupeau.apps.Poche.service.tasks.SyncOfflineChangesTask.run(SyncOfflineChangesTask.java:17)
 at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
 at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
 at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
 at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
 at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
 at java.lang.Thread.run(Thread.java:919)
```

**Comment by FrapiFrance** [comment]
the API I used since long time ago was https://app.wallabag.it

Just tried with a trailing / https://app.wallabag.it/
Worked on the Android app...

Can't understand what changes, maybe linked to let's encrypt issue ?

Anyway, if Android App works, now we should be able to have plop reader works too, I will see that

**Comment by FrapiFrance** [comment]
well, I'm really afraid it's a https issue on pocketbook

**Comment by FrapiFrance** [comment]
My plop-reader app (http://plop-reader.pascal-martin.fr/ ) on PocketBook/Vivlio Touch HD reader won't work with httpS since october.
Do you have a plan to offer an http API access ?

**Comment by nicosomb** [comment]
Hello @FrapiFrance

If I understand, the issue is on Plop reader side?

**Comment by FrapiFrance** [comment]
Well, yes, m'y pocketbook app won't support SECURE https anymore.
So can you have an http (not s) endpoint on wallabag ?

(Sorry I did not see your question before)

**Comment by j0k3r** [comment]
I don't think it'll be possible

**Comment by FrapiFrance** [comment]
Ok, copy that.
C'est pas grave pour moi.
Merci !
