### ISSUE TITLE
Erreur Serveur - fetching big pdf file

### ISSUE THREAD

**Issue by jimigwell** [wallabag/wallabag#5993]
Tout d'abord bonjour et bravo pour cette petite perle qu'est wallabag.

J'ai voulu mettre de coté l'url direct du Frido (https://laurent.claessens-donadello.eu/pdf/lefrido.pdf), un livre libre de mathématiques qui fait environ 13mo. 
Wallabag essaie de fetcher tout le contenu du livre hors je n'ai pas toucher a la limite par défaut d'upload php qui doit je pense etre de 2mo.

J'ai donc le droit a cette erreur :
`Erreur serveur
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
Pile d'erreur :
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
	at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
	at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
	at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
	at wallabag.apiwrapper.WallabagService.addArticle(WallabagService.java:236)
	at wallabag.apiwrapper.AddArticleBuilder.execute(AddArticleBuilder.java:73)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.addLink(OfflineChangesSynchronizer.java:252)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncOfflineQueue(OfflineChangesSynchronizer.java:146)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.synchronize(OfflineChangesSynchronizer.java:68)
	at fr.gaulupeau.apps.Poche.service.tasks.SyncOfflineChangesTask.run(SyncOfflineChangesTask.java:17)
	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
	at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
	at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
	at `java.lang.Thread.run(Thread.java:920)
`

 
J'ai essayer de vider le cache avec l'outil de commande et redémarrer le serveur mais sans succès . Wallabag continue a vouloir récupérer ce fichier.
Y a til une liste des actions en cours ou des url envoyées a wallabag ?
Commcnt supprimer le dernier élément envoyé a mon instance de wallabag ?

Mille merci d'avance

**Comment by j0k3r** [comment]
Tu l'as ajouté depuis l'app Android ?
Est-ce que l'app ne tente pas sans cesse d'ajouter l'url quoi que tu fasses côté serveur ?
poke @tcitworld

**Comment by jimigwell** [comment]
Effectivement je l'ai ajouté par l'app android.

Je viens de désinstaller complètement l'application et ses données mais le message réapparait après réinstallation.

Je peux ajouter un article depuis l'instance directement mais ca ne fonctionne pas via l'api (sur firefox).

**Comment by jimigwell** [comment]
Last update fixed it
