### ISSUE TITLE
Fatal error on upgrading (ubuntu 22.04)

### ISSUE THREAD

**Issue by rogorido** [wallabag/wallabag#6303]
Hi, I try to upgrade from v2.5.2 to 2.5.4 in ubuntu 22.04 with 
`sudo -u www-data make update` 

and I get the following error: 
```
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap                                                                                                    
PHP Fatal error:  Uncaught TypeError: Symfony\Component\Process\Process::__construct(): Argument #1 ($command) must be of type array, string given, called in /var/www/wallabag/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php on line 310 and defined in /usr/share/php/Symfony/Component/Process/Process.php:143
Stack trace:
#0 /var/www/wallabag/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php(310): Symfony\Component\Process\Process->__construct()
#1 /var/www/wallabag/vendor/sensio/distribution-bundle/Composer/ScriptHandler.php(88): Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::executeBuildBootstrap()
#2 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(389): Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap()
#3 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(238): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript()
#4 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(104): Composer\EventDispatcher\EventDispatcher->doDispatch()
#5 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(218): Composer\EventDispatcher\EventDispatcher->dispatch()
#6 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(119): Composer\EventDispatcher\EventDispatcher->doDispatch()
#7 /usr/share/php/Composer/Installer.php(372): Composer\EventDispatcher\EventDispatcher->dispatchScript()
#8 /usr/share/php/Composer/Command/InstallCommand.php(139): Composer\Installer->run()
#9 /usr/share/php/Symfony/Component/Console/Command/Command.php(298): Composer\Command\InstallCommand->execute()
#10 /usr/share/php/Symfony/Component/Console/Application.php(1015): Symfony\Component\Console\Command\Command->run()
#11 /usr/share/php/Symfony/Component/Console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#12 /usr/share/php/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#13 /usr/share/php/Symfony/Component/Console/Application.php(171): Composer\Console\Application->doRun()
#14 /usr/share/php/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#15 /usr/bin/composer(84): Composer\Console\Application->run()
#16 {main}
  thrown in /usr/share/php/Symfony/Component/Process/Process.php on line 143
```

Version:      2.5.2
Installation: git clone
PHP version:  8.1.2
OS:          ubuntu 22.04
Database:     PostgreSQL
Parameters:   Paste the content of your app/config/parameters.yml (hide sensitive stuff if you want)

**Comment by MoriarT3a** [comment]
The only way I can update since a few versions is to go to the wallabag folder and run

`sudo -u www-data bash scripts/update.sh prod`

Maybe this helps you, too.

**Comment by nicosomb** [comment]
@rogorido did you manage to update your instance?
