### ISSUE TITLE
500 Internal server error and impossible to sync via android app after upgrading wallabag docker image to 2.5.4

### ISSUE THREAD

**Issue by garret** [wallabag/wallabag#6321]
### Environment

* **Version**: 2.5.4
* **Installation**: Docker image
* **PHP version**: Don't know, I guess the one which comes inside the docker image?
* **OS**: Raspberry Pi OS (64bit) on a Raspberry Pi 4 (4GB)
* **Database**: SQLite
* **Parameters**: 

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

  ```
    wallabag:
        ports:
            - 80:80
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TIMEZONE}
            - SYMFONY__ENV__DOMAIN_NAME=${SYMFONY__ENV__DOMAIN_NAME}
            - SYMFONY__ENV__REDIS_HOST=wallabag-redis
            - SYMFONY__ENV__REDIS_PORT=6385
        volumes:
            - ${CONFIG_FOLDER}/wallabag/images:/var/www/wallabag/web/assets/images
            - ${CONFIG_FOLDER}/wallabag/data:/var/www/wallabag/data
            - ${CONFIG_FOLDER}/wallabag/AppKernel.php:/var/www/wallabag/app/AppKernel.php
        healthcheck:
            test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
            interval: 1m
            timeout: 3s
        depends_on:
            - wallabag-redis
        # labels:
        #    - com.centurylinklabs.watchtower.enable=false
        container_name: wallabag
        restart: unless-stopped
        image: wallabag/wallabag

    wallabag-redis:
        container_name: wallabag-redis
        image: redis:alpine
        restart: unless-stopped
        ports:
            - 6385:6379
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 20s
            timeout: 3s
  ```
</details>

### What steps will reproduce the bug?

I have had running wallabag for more than a year but since I upgraded via docker to the latest version of wallabag (2.5.4) I get an error when accessing the web interface of wallabag: 

![image](https://user-images.githubusercontent.com/27555/220045521-548293d6-2334-4a9f-a1f1-d678b67b7057.png)

<details>
  <summary>Error as text:</summary>

  ```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 
  ```
</details>

However, if I force an update of the page (and also after accessing again the same page after the "forceful update"), wallabag seems to return working:
![image](https://user-images.githubusercontent.com/27555/220046049-1cd14514-40e2-4c0c-a9d0-1521b0c74ac6.png)

Still though, the wallabag app on Android seems can't synchronize anymore with the server as I always get this error notification when trying to sync: 

![image](https://user-images.githubusercontent.com/27555/220046604-698f5717-daad-49df-b81c-661c56cadb53.png)

<details>
  <summary>Error as text:</summary>

  ```
Server error
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 Internal Server Error
Stacktrace:
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 Internal Server Error
	at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
	at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
	at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
	at wallabag.apiwrapper.WallabagService.deleteArticleWithId(WallabagService.java:723)
	at wallabag.apiwrapper.WallabagService.lambda$deleteArticle$3$WallabagService(WallabagService.java:664)
	at wallabag.apiwrapper.-$$Lambda$WallabagService$aW6rQND-Uyzlyhfan70BXqu1nnU.run(Unknown Source:6)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:140)
	at wallabag.apiwrapper.WallabagService.deleteArticle(WallabagService.java:662)
	at wallabag.apiwrapper.WallabagService.deleteArticle(WallabagService.java:638)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncOfflineQueue(OfflineChangesSynchronizer.java:138)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.synchronize(OfflineChangesSynchronizer.java:68)
	at fr.gaulupeau.apps.Poche.service.tasks.SyncOfflineChangesTask.run(SyncOfflineChangesTask.java:17)
	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
	at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
	at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)
  ```
</details>

Nothing suspicious seems to happen when I look at the docker log of the container: 

<details>
  <summary>Docker container log:</summary>

  ```
2023-02-20T07:44:36.052825334Z 127.0.0.1 - - [20/Feb/2023:08:44:36 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:44:36.578983514Z 127.0.0.1 - - [20/Feb/2023:08:44:36 +0100] "GET /login HTTP/1.1" 200 5083 "-" "Wget"
2023-02-20T07:45:37.262839977Z 127.0.0.1 - - [20/Feb/2023:08:45:37 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:45:37.927993928Z 127.0.0.1 - - [20/Feb/2023:08:45:37 +0100] "GET /login HTTP/1.1" 200 5083 "-" "Wget"
2023-02-20T07:46:38.761605973Z 127.0.0.1 - - [20/Feb/2023:08:46:38 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:46:39.317474267Z 127.0.0.1 - - [20/Feb/2023:08:46:39 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
2023-02-20T07:47:40.145495594Z 127.0.0.1 - - [20/Feb/2023:08:47:40 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:47:40.696214479Z 127.0.0.1 - - [20/Feb/2023:08:47:40 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
2023-02-20T07:48:41.441663962Z 127.0.0.1 - - [20/Feb/2023:08:48:41 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:48:42.055270001Z 127.0.0.1 - - [20/Feb/2023:08:48:42 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
2023-02-20T07:49:42.872389268Z 127.0.0.1 - - [20/Feb/2023:08:49:42 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:49:43.480046830Z 127.0.0.1 - - [20/Feb/2023:08:49:43 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
2023-02-20T07:50:44.240930420Z 127.0.0.1 - - [20/Feb/2023:08:50:44 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:50:44.786696762Z 127.0.0.1 - - [20/Feb/2023:08:50:44 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
2023-02-20T07:51:45.505551317Z 127.0.0.1 - - [20/Feb/2023:08:51:45 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:51:46.054001119Z 127.0.0.1 - - [20/Feb/2023:08:51:46 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
2023-02-20T07:52:46.766495107Z 127.0.0.1 - - [20/Feb/2023:08:52:46 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:52:47.384148257Z 127.0.0.1 - - [20/Feb/2023:08:52:47 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
2023-02-20T07:53:48.226193119Z 127.0.0.1 - - [20/Feb/2023:08:53:48 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:53:48.810409121Z 127.0.0.1 - - [20/Feb/2023:08:53:48 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
2023-02-20T07:54:49.560640966Z 127.0.0.1 - - [20/Feb/2023:08:54:49 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:54:50.253263254Z 127.0.0.1 - - [20/Feb/2023:08:54:50 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
2023-02-20T07:55:51.024556802Z 127.0.0.1 - - [20/Feb/2023:08:55:51 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:55:51.533229368Z 127.0.0.1 - - [20/Feb/2023:08:55:51 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
2023-02-20T07:56:32.849897010Z 10.10.10.4 - - [20/Feb/2023:08:56:32 +0100] "GET / HTTP/1.1" 200 7975 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
2023-02-20T07:56:33.801476302Z 10.10.10.4 - - [20/Feb/2023:08:56:33 +0100] "GET /js/routing?callback=fos.Router.setData HTTP/1.1" 200 390 "http://10.10.10.10:8383/" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
2023-02-20T07:56:34.081486805Z 10.10.10.4 - - [20/Feb/2023:08:56:34 +0100] "GET /wallassets/fonts/MaterialIcons-Regular.woff2 HTTP/1.1" 200 44907 "http://10.10.10.10:8383/wallassets/material.css" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
2023-02-20T07:56:52.213654269Z 127.0.0.1 - - [20/Feb/2023:08:56:52 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:56:52.873147256Z 127.0.0.1 - - [20/Feb/2023:08:56:52 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
2023-02-20T07:57:53.581159541Z 127.0.0.1 - - [20/Feb/2023:08:57:53 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:57:54.250528381Z 127.0.0.1 - - [20/Feb/2023:08:57:54 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
2023-02-20T07:58:10.925121999Z 10.10.10.2 - - [20/Feb/2023:08:58:10 +0100] "GET /api/version.json HTTP/1.1" 200 38 "-" "okhttp/4.9.1"
2023-02-20T07:58:11.568710655Z 10.10.10.2 - - [20/Feb/2023:08:58:11 +0100] "POST /oauth/v2/token HTTP/1.1" 500 1143 "-" "okhttp/4.9.1"
2023-02-20T07:58:12.364311429Z 10.10.10.2 - - [20/Feb/2023:08:58:12 +0100] "POST /oauth/v2/token HTTP/1.1" 500 1143 "-" "okhttp/4.9.1"
2023-02-20T07:58:30.061775006Z 10.10.10.2 - - [20/Feb/2023:08:58:30 +0100] "POST /oauth/v2/token HTTP/1.1" 500 1139 "-" "okhttp/4.9.1"
2023-02-20T07:58:54.997411579Z 127.0.0.1 - - [20/Feb/2023:08:58:54 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:58:55.764592025Z 127.0.0.1 - - [20/Feb/2023:08:58:55 +0100] "GET /login HTTP/1.1" 200 5072 "-" "Wget"
2023-02-20T07:59:56.506984033Z 127.0.0.1 - - [20/Feb/2023:08:59:56 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T07:59:57.035881789Z 127.0.0.1 - - [20/Feb/2023:08:59:57 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
2023-02-20T08:00:57.806350120Z 127.0.0.1 - - [20/Feb/2023:09:00:57 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T08:00:58.335032451Z 127.0.0.1 - - [20/Feb/2023:09:00:58 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
2023-02-20T08:01:09.864711876Z 10.10.10.4 - - [20/Feb/2023:09:01:09 +0100] "GET /config HTTP/1.1" 200 7174 "http://10.10.10.10:8383/" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
2023-02-20T08:01:10.609517331Z 10.10.10.4 - - [20/Feb/2023:09:01:10 +0100] "GET /js/routing?callback=fos.Router.setData HTTP/1.1" 200 390 "http://10.10.10.10:8383/config" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
2023-02-20T08:01:16.802403571Z 10.10.10.4 - - [20/Feb/2023:09:01:16 +0100] "GET /about HTTP/1.1" 200 4506 "http://10.10.10.10:8383/config" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
2023-02-20T08:01:17.493894873Z 10.10.10.4 - - [20/Feb/2023:09:01:17 +0100] "GET /js/routing?callback=fos.Router.setData HTTP/1.1" 200 390 "http://10.10.10.10:8383/about" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
2023-02-20T08:01:58.975457528Z 127.0.0.1 - - [20/Feb/2023:09:01:58 +0100] "GET / HTTP/1.1" 302 346 "-" "Wget"
2023-02-20T08:01:59.613382197Z 127.0.0.1 - - [20/Feb/2023:09:01:59 +0100] "GET /login HTTP/1.1" 200 3850 "-" "Wget"
  ```
</details>

Could you help me understanding what is happening? 
Thank you very much in advance. 

**EDIT:** I tried to delete an article from the web interface and I get this error: 

![image](https://user-images.githubusercontent.com/27555/220049016-84af0d14-c66b-4c22-b51f-fb7d63c1d802.png)

<details>
  <summary>Error as text:</summary>

  ```
500: Internal Server Error

An exception occurred while executing 'DELETE FROM "wallabag_entry" WHERE id = ?' with params [392]: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database
  ```
</details>

I don't know if that can help as is part of the problem or is a new issue though :/

**Comment by j0k3r** [comment]
Might be the same problem as https://github.com/wallabag/docker/issues/316
Could you show us log from `var/log/*` ?

**Comment by garret** [comment]
@j0k3r It seems pretty empty and, for some reason, it can't `cat` the files inside the `nginx` folder, it just hangs and have to manually terminate it. 

![image](https://user-images.githubusercontent.com/27555/220051499-f3368f19-474f-45b5-bed8-6a68cebc603f.png)

**Comment by garret** [comment]
Solved by doing https://github.com/wallabag/docker/issues/316#issuecomment-1465048886
