### ISSUE TITLE
Error 502 from Android app

### ISSUE THREAD

**Issue by enrique-mp** [wallabag/wallabag#6428]
### Environment
* **Version**:
* Version: 2.5.4
* **Installation**:
* Docker self-hosted
* **PHP version**:
* 8.1.15
* **OS**:
* Ubuntu Server 22.04
* **Database**:
* sqlite
* **Parameters**:

<details>
  <summary>My <code>app/config/parameters.yml</code> is:</summary>

```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://wallabag.enriquemorales.ml'
    server_name: 'emp links'
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: 25
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: ovmpmAWXRCabNlMgzlzFXDYmCFfzGv
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
 ```

</details>

### What steps will reproduce the bug?

Every time I try to save an article or update the Wallabag App

```
 Error: wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 502
Traza de error:
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 502
at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
at wallabag.apiwrapper.WallabagService.getTags(WallabagService.java:1037)
at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.initTagMapsFromServer(ArticleUpdater.java:216)
at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.performUpdate(ArticleUpdater.java:161)
at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.update(ArticleUpdater.java:127)
at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.updateArticles(ArticleUpdateWorker.java:77)
at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.update(ArticleUpdateWorker.java:37)
at fr.ga
```

**Comment by j0k3r** [comment]
Could you check for logs on wallabag side?
Logs from the app doesn't help us here.
